- src/main/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdvice.kt
- src/main/kotlin/com/epam/brn/dto/ErrorResponse.kt
- src/main/kotlin/com/epam/brn/exception/NoDataFoundException.kt
- src/test/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdviceTest.kt
EPAMLABSBRN-65
add ExceptionControllerAdvice
> EPAMLABSBRN-65

- build.gradle
- src/main/kotlin/com/epam/brn/controller/TaskController.kt
- src/main/kotlin/com/epam/brn/repo/TaskRepository.kt
- src/main/kotlin/com/epam/brn/service/TaskService.kt
- src/test/kotlin/com/epam/brn/repo/BaseTest.kt
- src/test/kotlin/com/epam/brn/repo/TaskRepositoryTest.kt
- src/test/kotlin/com/epam/brn/service/TaskServiceTest.kt
- src/test/resources/application.properties
- embedded h2 for repository testing
> EPMLABSBRN-65 new unit tests for tasks repo and service

- README.md
Added instructions on how to start BE
> Docker start instructions

- .github/workflows/frontend-test.yml
This adds github-action for running FE tests
> added FE test workflow

- src/main/kotlin/com/epam/brn/controller/SeriesController.kt
- src/main/kotlin/com/epam/brn/repo/SeriesRepository.kt
- src/main/kotlin/com/epam/brn/service/LoadHandBook.kt
- src/main/kotlin/com/epam/brn/service/SeriesService.kt
- src/test/kotlin/com/epam/brn/controller/SeriesControllerTest.kt
- src/test/kotlin/com/epam/brn/service/SeriesServiceTest.kt
EPAMLABSBRN-44
fix getting series for groupId
+ tests
+ load initial data
> EPAMLABSBRN-44 getting series for groupId

- src/main/resources/application-prod.properties
**EPMLABSBRN-80** fix docker compose file to run it on remote instance
**CONTENTS**
Removed 8081 mapping on prod profile. It should be 8080.
> EPMLABSBRN-80 fix docker compose file to run it on remote instance

- frontend/app/components/exercise-navigation/template.hbs
- frontend/app/components/series-navigation/template.hbs
- frontend/app/components/task-player/template.hbs
- frontend/app/index.html
- frontend/app/styles/app.css
- frontend/app/templates/application.hbs
- frontend/app/templates/series.hbs
- frontend/package.json
[EPMLABSBRN-60](https://jira.epam.com/jira/browse/EPMLABSBRN-60)
**Utilized** blaze-ui components for the app
> blazeUI usage

- README.md
- build.gradle
- src/main/kotlin/com/epam/brn/model/Exercise.kt
- src/main/kotlin/com/epam/brn/model/Series.kt
- src/main/kotlin/com/epam/brn/model/Task.kt
- src/test/resources/application.properties
EPMLABSBRN-77 fix minor issues
- fix for Idea + gradle build described [here]( https://youtrack.jetbrains.com/issue/IDEA-193219?_ga=2.101799425.1855621572.1571691456-75860811.1570710027)
- avoiding eager initialization for exercises during getting a task, @ManyToOne default value is EAGER
- add properties for embedded DB
- typos
> EPMLABSBRN-77 fix minor issues

- .github/pull_request_template.md
This will help with consistent PRs descriptions
More info – https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
> UI added Pull request template

- frontend/app/components/exercise-navigation/styles.css
- frontend/app/components/series-navigation/styles.css
- frontend/app/components/task-player/styles.css
- frontend/app/styles/app.css
- frontend/ember-cli-build.js
- frontend/package.json
- frontend/yarn.lock
separate styles for components
> EPMLABSBRN-76

- build.gradle
- src/test/kotlin/com/epam/brn/integration/SeriesControllerIT.kt
EPAMLABSBRN-34 create first integr test SeriesControllerIT
add integration test
> EPAMLABSBRN-34 create first integr test SeriesControllerIT

- .github/workflows/frontend-test.yml
- frontend/mirage/config.js
- frontend/package.json
- frontend/yarn.lock
- run_fe_tests.sh
[EPMLABSBRN-92](https://jira.epam.com/jira/browse/EPMLABSBRN-92)
Code coverage monitor for FE
> Epmlabsbrn 92 FE code coverage

- src/main/kotlin/com/epam/brn/constant/BrnFlags.kt
- src/main/kotlin/com/epam/brn/constant/BrnParams.kt
- src/main/kotlin/com/epam/brn/constant/BrnPath.kt
- src/main/kotlin/com/epam/brn/controller/SeriesController.kt
- src/main/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdvice.kt
- src/main/kotlin/com/epam/brn/dto/BaseResponseDto.kt
- src/main/kotlin/com/epam/brn/dto/ExerciseDto.kt
- src/main/kotlin/com/epam/brn/dto/SeriesDto.kt
- src/main/kotlin/com/epam/brn/model/Exercise.kt
- src/main/kotlin/com/epam/brn/model/ExerciseGroup.kt
- src/main/kotlin/com/epam/brn/model/Series.kt
- src/main/kotlin/com/epam/brn/repo/SeriesRepository.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/main/kotlin/com/epam/brn/service/SeriesService.kt
- src/test/kotlin/com/epam/brn/controller/SeriesControllerTest.kt
- src/test/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdviceTest.kt
- src/test/kotlin/com/epam/brn/integration/SeriesControllerIT.kt
- src/test/kotlin/com/epam/brn/service/SeriesServiceTest.kt
EPAMLABSBRN-94 remake series end-point to support new naming conversion
> EPAMLABSBRN-94 remake series end-point to support new naming conversion

- build.gradle
- src/main/kotlin/com/epam/brn/controller/TaskController.kt
- src/main/kotlin/com/epam/brn/repo/TaskRepository.kt
- src/main/kotlin/com/epam/brn/service/TaskService.kt
- src/test/kotlin/com/epam/brn/controller/ExerciseControllerTest.kt
- src/test/kotlin/com/epam/brn/controller/GroupControllerTest.kt
- src/test/kotlin/com/epam/brn/controller/TaskControllerTest.kt
- src/test/kotlin/com/epam/brn/integration/TaskControllerIT.kt
- src/test/kotlin/com/epam/brn/job/UploadFileJobRunnerTest.kt
- src/test/kotlin/com/epam/brn/repo/BaseTest.kt
- src/test/kotlin/com/epam/brn/repo/TaskRepositoryTest.kt
- src/test/kotlin/com/epam/brn/service/TaskServiceTest.kt
- added logic to Controller -> Service -> Repository levels
- test for levels are listed above
- fixed issues and improvements
- to avoid 'Unchecked cast:' warnings added @Suppress("UNCHECKED_CAST")
for special cases
- added kotlin-test for testing exception cases using assertFailsWith
> EPMLABSBRN-95 update endpoint to get tasks

- Dockerfile_frontend
- build_scripts/build_frontend.sh
- docker-compose.yml
[EPMLABSBRN-115](https://jira.epam.com/jira/browse/EPMLABSBRN-115)
BRN frontend containerization
> EPMLABSBRN-115 containerize BRN frontend

- src/main/kotlin/com/epam/brn/service/LoadHandBook.kt
EPMLABSBRN-114 Back-end: load initial data only in dev/prod profile
add support profiles active for load initial data
> EPMLABSBRN-114 Back-end: load initial data only in dev/prod profile

- api-contract/api.raml
- src/main/kotlin/com/epam/brn/constant/BrnPath.kt
- src/main/kotlin/com/epam/brn/controller/LoadFilesController.kt
- src/main/kotlin/com/epam/brn/controller/TaskController.kt
- src/test/kotlin/com/epam/brn/controller/LoadFilesControllerTest.kt
[EPMLABSBRN-111](https://jira.epam.com/jira/browse/EPMLABSBRN-111)
- Added load task file end-point to api.raml
-  Moved api for load files to separate controller LoadFilesController
> [EPMLABSBRN-111] - improve load file end-point

- build.gradle
- src/main/kotlin/com/epam/brn/converter/StudyHistoryConverter.kt
- src/main/kotlin/com/epam/brn/service/StudyHistoryService.kt
- src/test/kotlin/com/epam/brn/service/StudyHistoryServiceTest.kt
EPMLABSBRN-109
try to fix jenkins
> EPMLABSBRN-109

- build.gradle
- src/main/kotlin/com/epam/brn/converter/StudyHistoryConverter.kt
- src/main/kotlin/com/epam/brn/service/StudyHistoryService.kt
- src/test/kotlin/com/epam/brn/service/StudyHistoryServiceTest.kt
> Revert "EPMLABSBRN-109"

- frontend/.istanbul.yml
- frontend/README.md
- frontend/app/adapters/application.js
- frontend/app/routes/error.js
- frontend/app/routes/series.js
- frontend/app/serializers/application.js
- frontend/app/templates/error.hbs
- frontend/app/templates/group.hbs
- frontend/config/environment.js
- frontend/package.json
- frontend/tests/unit/routes/error-test.js
[EPMLABSBRN-118](https://jira.epam.com/jira/browse/EPMLABSBRN-118)
Using real BE as data source.
**note:**
Still waiting for https://jira.epam.com/jira/browse/EPMLABSBRN-106 to fully work as expected
> EPMLABSBRN-118 Using real BE API

- api-contract/api.raml
- src/main/kotlin/com/epam/brn/constant/BrnCsvTypes.kt
- src/main/kotlin/com/epam/brn/job/CsvUtils.kt
- src/main/kotlin/com/epam/brn/job/csv/task/impl/UploadTaskFromCsvJob.kt
- src/main/kotlin/com/epam/brn/service/parsers/csv/CSVParserService.kt
- src/main/kotlin/com/epam/brn/service/parsers/csv/converter/impl/TaskCsvToTaskModelConverter.kt
- src/main/kotlin/com/epam/brn/service/parsers/csv/dto/TaskCsv.kt
- src/test/resources/inputData/tasks/tasks.csv
[EPMLABSBRN-120](https://jira.epam.com/jira/browse/EPMLABSBRN-120)
- Fixed task file format to:
exerciseId orderNumber word fileName words
1 1 бал no_noise/бал.mp3 (бум,быль,боль,зал,мал)
1 2 бум no_noise/бум.mp3 (зум,кум,лунь,дума,куб)
> [EPMLABSBRN-120] - fix loading format file

- Dockerfile_frontend
- frontend/app/adapters/application.js
- frontend/config/environment.js
- frontend/mirage/config.js
- frontend/package.json
- frontend/yarn.lock
[EPMLABSBRN-126](https://jira.epam.com/jira/browse/EPMLABSBRN-126)
`docker-compose up` will spin-up whole application
> EPMLABSBRN-126 FE deploy

- api-contract/api.raml
- src/main/kotlin/com/epam/brn/constant/BrnPath.kt
EPMLABSBRN-136
add `/api` to all end-points
> EPMLABSBRN-136 add `/api` to all end-points

- Dockerfile_frontend
- default.conf
[EPMLABSBRN-126](https://jira.epam.com/jira/browse/EPMLABSBRN-126)
- added nginx configuration to connect /api endpoint to brb container
> EPMLABSBRN-126: devops: deploy front-end (ember) to our instance

- src/main/kotlin/com/epam/brn/service/parsers/csv/converter/impl/TaskCsvToTaskModelConverter.kt
- src/main/resources/application.properties
- src/test/resources/application.properties
[EPMLABSBRN-129](https://jira.epam.com/jira/browse/EPMLABSBRN-129)
- Fixes audio_file_url setting in load job
> [EPMLABSBRN-129] - fix audio_file_url setting in load job

- Dockerfile_frontend
- default.conf
added /admin rule
- fixed issue with single page application
> Fix of nginx config for Single Page Application

- frontend-angular/angular.json
- frontend-angular/package.json
- frontend-angular/src/app/admin/admin-page.component.html
- frontend-angular/src/app/admin/admin-page.component.scss
- frontend-angular/src/app/admin/admin-page.component.ts
- frontend-angular/src/app/admin/admin.module.ts
- frontend-angular/src/app/admin/components/home/home.component.html
- frontend-angular/src/app/admin/components/home/home.component.scss
- frontend-angular/src/app/admin/components/home/home.component.spec.ts
- frontend-angular/src/app/admin/components/home/home.component.ts
- frontend-angular/src/app/admin/components/load-file/load-file.component.html
- frontend-angular/src/app/admin/components/load-file/load-file.component.ts
- frontend-angular/src/app/admin/components/load-tasks/load-tasks.component.html
- frontend-angular/src/app/admin/components/load-tasks/load-tasks.component.ts
- frontend-angular/src/app/admin/services/admin.service.ts
- frontend-angular/src/app/app-routing.module.ts
- frontend-angular/src/app/app.component.html
- frontend-angular/src/app/app.component.ts
- frontend-angular/src/app/app.module.ts
- frontend-angular/src/app/shared/shared.module.ts
- frontend-angular/src/app/shared/upload-file/service/upload.service.spec.ts
- frontend-angular/src/app/shared/upload-file/service/upload.service.ts
- frontend-angular/src/app/shared/upload-file/service/utils.ts
- frontend-angular/src/app/shared/upload-file/upload-file.component.html
- frontend-angular/src/app/shared/upload-file/upload-file.component.ts
- frontend-angular/src/app/shared/upload-file/upload-file.module.ts
- frontend-angular/src/proxy.conf.json
EPMLABSBRN-90
- integrated backend API with frontend services
- implemented basic upload module
- implemented full file upload
> EPMLABSBRN-90

- src/main/kotlin/com/epam/brn/model/Exercise.kt
- src/main/kotlin/com/epam/brn/model/ExerciseGroup.kt
- src/main/kotlin/com/epam/brn/model/Series.kt
- src/main/kotlin/com/epam/brn/service/LoadHandBook.kt
EPMLABSBRN-128
fix data order on creation step
> EPMLABSBRN-128

- frontend/app/models/task.js
- frontend/app/serializers/task.js
- frontend/tests/unit/serializers/task-test.js
[EPMLABSBRN-140](https://jira.epam.com/jira/browse/EPMLABSBRN-140)
**Description**: task serializer
> EPMLABSBRN-140

- frontend/app/components/series-navigation/template.hbs
- frontend/app/serializers/application.js
- frontend/app/serializers/exercise.js
- frontend/app/serializers/series.js
- frontend/app/serializers/task.js
- frontend/package.json
- frontend/tests/integration/components/series-navigation/component-test.js
- frontend/tests/integration/components/series-navigation/test-support/page-object.js
[EPMLABSBRN-141](https://jira.epam.com/jira/browse/EPMLABSBRN-141)
Fixes:
- exercises ordering
- audio urls
- series serialization (fixes breadcrumbs on "task" page)
> Exercises order

- frontend/app/components/exercise-navigation/styles.css
- frontend/app/components/exercise-navigation/template.hbs
- frontend/app/components/task-player/component.js
- frontend/app/helpers/html-safe.js
- frontend/app/models/task.js
- frontend/tests/integration/components/exercise-navigation/component-test.js
- frontend/tests/integration/components/exercise-navigation/test-support/page-object.js
- frontend/tests/integration/helpers/html-safe-test.js
[EPMLABSBRN-57](https://jira.epam.com/jira/browse/EPMLABSBRN-57)
**Description**: tasks navigator adjustments
> EPMLABSBRN-57 tasks navigator adjustments

- frontend/app/components/audio-player/component.js
- frontend/app/components/audio-player/styles.css
- frontend/app/components/audio-player/template.hbs
- frontend/app/components/task-player/template.hbs
- frontend/package.json
- frontend/tests/integration/components/audio-player/component-test.js
- frontend/tests/integration/components/audio-player/page-object.js
- frontend/tests/test-helper.js
- frontend/yarn.lock
[EPMLABSBRN-145](https://jira.epam.com/jira/browse/EPMLABSBRN-145)
**Description**: tests may fail, in progress
> Epmlabsbrn 145

- frontend/app/models/exercise.js
- frontend/app/routes/series.js
> FE adjustments for routing

- src/main/kotlin/com/epam/brn/controller/ExerciseController.kt
- src/main/kotlin/com/epam/brn/controller/GroupController.kt
- src/main/kotlin/com/epam/brn/controller/SeriesController.kt
- src/main/kotlin/com/epam/brn/controller/TaskController.kt
- src/main/kotlin/com/epam/brn/dto/BaseResponseDto.kt
- src/main/kotlin/com/epam/brn/model/Exercise.kt
- src/test/kotlin/com/epam/brn/controller/ExerciseControllerTest.kt
- src/test/kotlin/com/epam/brn/controller/GroupControllerTest.kt
- src/test/kotlin/com/epam/brn/controller/TaskControllerTest.kt
- src/test/kotlin/com/epam/brn/integration/ExercisesControllerIT.kt
- src/test/kotlin/com/epam/brn/integration/TaskControllerIT.kt
EPMLABSBRN-151
fix: add level to model -> dto convertion
EPMLABSBRN-124
single object in responce
> EPMLABSBRN-151, EPMLABSBRN-124 fix: add level to model -> dto convertion, single object in responce

- frontend/app/components/task-player/component.js
- frontend/app/components/task-player/styles.css
- frontend/app/components/task-player/template.hbs
- frontend/app/models/task.js
- frontend/app/serializers/task.js
- frontend/app/templates/series.hbs
[EPMLABSBRN-150](https://jira.epam.com/jira/browse/EPMLABSBRN-150)
**Description**: show picture after the right answer, if the task has it
> EPMLABSBRN-150 

- frontend/app/components/group-navigation/template.hbs
- frontend/app/models/series.js
- frontend/app/routes/series.js
- frontend/tests/acceptance/unaccessible-routes/unaccessible-routes-test.js
[EPMLABSBRN-153](https://jira.epam.com/jira/browse/EPMLABSBRN-153)
made series always accesable
> Epmlabsbrn 153 series always accesable

- frontend/app/components/audio-player/styles.css
- frontend/app/components/audio-player/template.hbs
- frontend/app/components/breadcrumbs/styles.css
- frontend/app/components/breadcrumbs/template.hbs
- frontend/app/components/exercise-navigation/template.hbs
- frontend/app/components/series-navigation/template.hbs
- frontend/app/components/task-player/styles.css
- frontend/app/components/task-player/template.hbs
- frontend/app/index.html
- frontend/app/styles/app.css
- frontend/app/templates/application.hbs
- frontend/app/templates/error.hbs
- frontend/app/templates/series.hbs
**Description**: EPMLABSBRN-remove-blazeUI
> EPMLABSBRN-remove-blazeUI

- frontend/app/components/exercise-navigation/template.hbs
- frontend/app/components/task-player/styles.css
- frontend/app/helpers/subtract.js
- frontend/app/models/completion-dependent.js
- frontend/app/models/series.js
- frontend/app/routes/series/exercise/task.js
- frontend/tests/acceptance/unaccessible-routes/test-support/page-object.js
- frontend/tests/acceptance/unaccessible-routes/unaccessible-routes-test.js
- frontend/tests/integration/helpers/subtract-test.js
[EPMLABSBRN-155](https://jira.epam.com/jira/browse/EPMLABSBRN-155)
**Description**: fix tasks markers' motions
> EPMLABSBRN-155 fix tasks markers' motions

- frontend/app/serializers/series.js
- src/main/kotlin/com/epam/brn/dto/SeriesDto.kt
- src/main/kotlin/com/epam/brn/dto/TaskDto.kt
- src/main/kotlin/com/epam/brn/model/Exercise.kt
- src/main/kotlin/com/epam/brn/model/ExerciseGroup.kt
- src/main/kotlin/com/epam/brn/model/Resource.kt
- src/main/kotlin/com/epam/brn/model/Series.kt
- src/main/kotlin/com/epam/brn/model/Task.kt
- src/test/kotlin/com/epam/brn/controller/TaskControllerTest.kt
EPMLABSBRN-143 
fix api format of return series dto accoding to api.raml
> EPMLABSBRN-143 fix api format of return series dto accoding to api.raml

- build.gradle
- gradle.properties
- settings.gradle
> EPMLABSBRN-162 Improve build script

- src/main/kotlin/com/epam/brn/constant/BrnParams.kt
- src/main/kotlin/com/epam/brn/controller/LoadFilesController.kt
- src/main/kotlin/com/epam/brn/job/csv/task/UploadFromCsvJob.kt
- src/main/kotlin/com/epam/brn/job/csv/task/impl/UploadTaskFromCsvJob.kt
- src/main/kotlin/com/epam/brn/service/parsers/csv/CSVParserService.kt
- src/test/kotlin/com/epam/brn/service/parsers/csv/CSVParserServiceTest.kt
[EPMLABSBRN-133](https://jira.epam.com/jira/browse/EPMLABSBRN-133)
Added returning information about loading task files to end-point response
> [EPMLABSBRN-133] - PUT files end-point: add to response body all files lines which was not added to db

- api-contract/api.raml
- api-contract/samples/exercise_for_sequence_words_series.json
- api-contract/samples/exercise_for_single_words_series.json
- api-contract/samples/exercises_for_sequence_words_series.json
- api-contract/samples/exercises_for_single_words_series.json
- src/main/kotlin/com/epam/brn/dto/ExerciseDto.kt
- src/main/kotlin/com/epam/brn/dto/ShortTaskDto.kt
- src/main/kotlin/com/epam/brn/model/Exercise.kt
EPMLABSBRN-173 add exType to exDto
> EPMLABSBRN-173  add exType to exDto

- src/main/kotlin/com/epam/brn/model/Exercise.kt
- src/main/kotlin/com/epam/brn/repo/ExerciseRepository.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/test/kotlin/com/epam/brn/service/ExerciseServiceTest.kt
EPMLABSBRN-184 add constrain to exercise: name + level
> EPMLABSBRN-184 add constrain to exercise: name + level

- frontend/ember-cli-build.js
[EPMLABSBRN-185](https://jira.epam.com/jira/browse/EPMLABSBRN-185)
> EPMLABSBRN-185 (#120) test selector

- frontend/app/components/audio-player/component.js
- frontend/app/components/progress-indicator/component.js
- frontend/app/components/progress-indicator/template.hbs
- frontend/app/components/task-player/words-sequences/component.js
- frontend/app/components/task-player/words-sequences/styles.css
- frontend/app/components/task-player/words-sequences/template.hbs
- frontend/app/components/text-image-button/template.hbs
- frontend/tests/integration/components/progress-indicator/component-test.js
[EPMLABSBRN-190](https://jira.epam.com/jira/browse/EPMLABSBRN-190)
> EPMLABSBRN-190

- .github/workflows/frontend-test.yml
> using upstream action to measure frontend code coverage now

- src/main/kotlin/com/epam/brn/controller/StudyHistoryController.kt
- src/main/kotlin/com/epam/brn/dto/StudyHistoryDto.kt
- src/main/kotlin/com/epam/brn/model/StudyHistory.kt
- src/main/kotlin/com/epam/brn/service/InitialDataLoader.kt
- src/main/kotlin/com/epam/brn/service/StudyHistoryService.kt
- src/test/kotlin/com/epam/brn/controller/StudyHistoryControllerTest.kt
- src/test/kotlin/com/epam/brn/service/StudyHistoryServiceTest.kt
Epmlabsbrn 167 
fix adding study_history rows,
some refactoring
> Epmlabsbrn 167 back-end: fix adding study_history rows

- api-contract/samples/exercise_for_single_words_series.json
- api-contract/samples/exercises_for_single_words_series.json
- src/main/kotlin/com/epam/brn/dto/ExerciseDto.kt
- src/main/kotlin/com/epam/brn/model/Exercise.kt
EPMLABSBRN-192 add flag avaliable to response ex dto
(temporary true, would add filling logic later)
> EPMLABSBRN-192 add flag avaliable to response ex dto (temporary true, would add filling logic later)

- .github/workflows/frontend-test.yml
- frontend/README.md
- frontend/package.json
- run_fe_tests.sh
> frontend tools cleanup

- frontend/app/components/timer/component.js
- frontend/app/components/timer/template.hbs
- frontend/app/services/studying-timer.js
- frontend/app/utils/custom-timeout.js
- frontend/config/environment.js
- frontend/ember-cli-build.js
- frontend/package.json
- frontend/tests/integration/components/timer/component-test.js
- frontend/tests/unit/utils/custom-timeout-test.js
- frontend/yarn.lock
[EPMLABSBRN-207](https://jira.epam.com/jira/browse/EPMLABSBRN-207)
**Description**: timer autopause
> EPMLABSBRN-207 timer autopause

- frontend/app/components/timer/component.js
- frontend/tests/integration/components/timer/component-test.js
[EPMLABSBRN-202](https://jira.epam.com/jira/browse/EPMLABSBRN-202)
**Description**: add hours to the timer widget
> EPMLABSBRN-202 

- frontend-angular/src/app/admin/components/load-file/load-file.component.ts
- frontend-angular/src/app/admin/components/load-tasks/load-tasks.component.html
- frontend-angular/src/app/admin/components/load-tasks/load-tasks.component.ts
- frontend-angular/src/app/shared/pure.ts
- frontend-angular/src/app/shared/upload-file/service/upload.service.ts
- frontend-angular/src/app/shared/upload-file/service/utils.ts
fixes loadTasks page should use API to upload file
> EPMLABSBRN-196 - fixes loadTasks page should use API to upload file

- frontend/app/components/audio-player/component.js
- frontend/app/components/audio-player/styles.css
- frontend/app/components/audio-player/template.hbs
- frontend/app/services/studying-timer.js
- frontend/tests/acceptance/task-flow/tasks-flow-test.js
- frontend/tests/integration/components/audio-player/component-test.js
[EPMLABSBRN-209](https://jira.epam.com/jira/browse/EPMLABSBRN-209)
**Description**: audio player progress indicator
> EPMLABSBRN-209

- frontend/app/components/task-player/component.js
- frontend/app/components/task-player/template.hbs
- frontend/app/components/timer/component.js
- frontend/app/services/studying-timer.js
[EPMLABSBRN-222](https://jira.epam.com/jira/browse/EPMLABSBRN-222)
**Description**: Forbid a task from starting after changing browser tabs if the task is not started yet
> EPMLABSBRN-222  Forbid a task from starting after changing browser tabs if the task is not started yet

- frontend/app/components/audio-player/component.js
**Description**: playing-btn-adjustment
> UI playing-btn-adjustment

- frontend/app/components/progress-indicator/component.js
- frontend/app/components/progress-indicator/template.hbs
- frontend/app/components/task-player/words-sequences/component.js
- frontend/app/models/task.js
- frontend/app/routes/group/series/exercise.js
- frontend/app/services/tasks-manager.js
- frontend/tests/integration/components/progress-indicator/component-test.js
- frontend/tests/integration/components/progress-indicator/test-support/helpers.js
[EPMLABSBRN-206](https://jira.epam.com/jira/browse/EPMLABSBRN-206)
**Description**: Progress bar should reset its state after all tasks of one type are finished
> EPMLABSBRN-206 Progress bar should reset its state after all tasks of one type are finished

- frontend/app/components/series-navigation/template.hbs
- frontend/app/models/completion-dependent.js
- frontend/app/models/exercise.js
- frontend/app/models/series.js
- frontend/app/utils/array-previous-items.js
- frontend/tests/acceptance/exercise-availability/exercises-availability-test.js
- frontend/tests/acceptance/exercise-availability/test-support/data-storage.js
- frontend/tests/acceptance/exercise-availability/test-support/page-object.js
- frontend/tests/acceptance/general-helpers.js
- frontend/tests/acceptance/task-flow/tasks-flow-test.js
- frontend/tests/acceptance/task-flow/test-support/helpers.js
- frontend/tests/acceptance/unaccessible-routes/test-support/helpers.js
- frontend/tests/integration/components/series-navigation/component-test.js
- frontend/tests/unit/utils/array-previous-items-test.js
[EPMLABSBRN-204](https://jira.epam.com/jira/browse/EPMLABSBRN-204)
**Description**: exercises availability changes
> Epmlabsbrn-204 - exercises opening(becoming available) order

- frontend-angular/src/app/admin/components/load-tasks/load-tasks.component.ts
fixes relative api url while uploading tasks file
> fixes relative api url while uploading tasks file

- frontend-angular/src/app/app.module.ts
- frontend-angular/src/app/shared/services/basic-auth.interceptor.service.ts
[EPMLABSBRN-245](https://jira.epam.com/jira/browse/EPMLABSBRN-245)
added basic auth header to admin app
> EPMLABSBRN-245 - added basic auth header to admin app

- frontend-angular/package.json
**Description**: 
switched admin-project to production mode
> fixes bundle size

- .githooks/commit-msg
- .githooks/pre-commit
- .githooks/pre-push
- Makefile
- build.gradle
[EPMLABSBRN-244](https://jira.epam.com/jira/browse/EPMLABSBRN-244)
githooks were added to the project:
- a command to set core.hooksPath was added to Makefile
- core.hooksPath automatically set during the build
> EPMLABSBRN-244 githooks were added to the repository

- frontend/app/templates/group.hbs
- frontend/app/templates/group/series/exercise.hbs
- frontend/config/environment.js
[EPMLABSBRN-188](https://jira.epam.com/jira/browse/EPMLABSBRN-188)
> EPMLABSBRN-188 - "Back" button in the exercise run mode

- .githooks/commit-msg
- src/main/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdvice.kt
- src/main/kotlin/com/epam/brn/model/StudyHistory.kt
- src/test/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdviceTest.kt
- src/test/kotlin/com/epam/brn/integration/ExercisesControllerIT.kt
- src/test/kotlin/com/epam/brn/integration/GroupControllerIT.kt
- src/test/kotlin/com/epam/brn/integration/SeriesControllerIT.kt
- src/test/kotlin/com/epam/brn/integration/TaskControllerIT.kt
- src/test/kotlin/com/epam/brn/service/parsers/csv/CSVParserServiceTest.kt
[EPMLABSBRN-259](https://jira.epam.com/jira/browse/EPMLABSBRN-259)
**Change from deprecated to recommend:**
**More improvements**
> EPMLABSBRN-259 change deprecated to recommend

- .github/workflows/gradle.yml
EPMLABSBRN-261 Fix gradle github action
> EPMLABSBRN-261 Fix gradle github action

- src/main/kotlin/com/epam/brn/model/Task.kt
EPMLABSBRN-213 add api for 3 series
CascadeType.MERGE -> CascadeType.ALL to unblock front-end, fix it later
> EPMLABSBRN-213 add api for 3 series

- .githooks/commit-msg
[EPMLABSBRN-262](https://jira.epam.com/jira/browse/EPMLABSBRN-262)
Prefix Merge or merge  was added for commit messages
> EPMLABSBRN-262 added prefix Merge or merge for commit messages

- src/main/kotlin/com/epam/brn/controller/GroupController.kt
- src/main/kotlin/com/epam/brn/job/csv/task/impl/UploadTaskFromCsvService.kt
- src/main/kotlin/com/epam/brn/model/Exercise.kt
- src/main/kotlin/com/epam/brn/model/Resource.kt
- src/main/kotlin/com/epam/brn/model/Series.kt
- src/main/kotlin/com/epam/brn/model/Task.kt
- src/main/kotlin/com/epam/brn/repo/ExerciseRepository.kt
- src/main/kotlin/com/epam/brn/repo/SeriesRepository.kt
- src/main/kotlin/com/epam/brn/service/ExerciseGroupsService.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/main/kotlin/com/epam/brn/service/InitialDataLoader.kt
- src/main/kotlin/com/epam/brn/service/ResourceService.kt
- src/main/kotlin/com/epam/brn/service/SeriesService.kt
- src/main/kotlin/com/epam/brn/service/parsers/csv/FirstSeriesCSVParserService.kt
- src/main/kotlin/com/epam/brn/service/parsers/csv/converter/impl/ExerciseCsvToExerciseModelConverter.kt
- src/main/kotlin/com/epam/brn/service/parsers/csv/converter/impl/ExerciseGroupCsvToExerciseGroupConverter.kt
- src/main/kotlin/com/epam/brn/service/parsers/csv/converter/impl/SeriesCsvToSeriesConverter.kt
- src/main/kotlin/com/epam/brn/service/parsers/csv/converter/impl/TaskCsvToTaskModelConverter.kt
- src/test/kotlin/com/epam/brn/controller/GroupControllerTest.kt
- src/test/kotlin/com/epam/brn/integration/CsvLoadingTestIT.kt
- src/test/kotlin/com/epam/brn/repo/BaseTest.kt
- src/test/kotlin/com/epam/brn/service/ExerciseGroupServiceTest.kt
- src/test/kotlin/com/epam/brn/service/ExerciseServiceTest.kt
- src/test/kotlin/com/epam/brn/service/parsers/csv/CSVParserServiceTest.kt
- src/test/kotlin/com/epam/brn/service/parsers/csv/FirstSeriesCSVParserServiceTest.kt
[EPMLABSBRN-236](https://jira.epam.com/jira/browse/EPMLABSBRN-236)
- Added common list of converters for parsing csv-files
- Splitted csv parser by series
> EPMLABSBRN-236 existing code refactoring - make one smart decision of processing files

- src/main/kotlin/com/epam/brn/job/csv/task/impl/UploadTaskFromCsvService.kt
- src/main/kotlin/com/epam/brn/service/TaskService.kt
- src/main/kotlin/com/epam/brn/service/parsers/csv/converter/impl/TaskCsvToTaskModelConverter.kt
EPMLABSBRN-279 fix wordType in resources
> EPMLABSBRN-279 fix wordType in resources

- src/main/kotlin/com/epam/brn/constant/WordTypeEnum.kt
- src/main/kotlin/com/epam/brn/service/parsers/csv/converter/impl/TaskCsvToTaskModelConverter.kt
- src/main/resources/initFiles/tasks_for_single_words_series.csv
EPMLABSBRN-279 fix wordType setting logic
> EPMLABSBRN-279 fix wordType setting logic

- api-contract/api.raml
- api-contract/samples/users_delete_response.json
- api-contract/samples/users_get_response.json
- api-contract/samples/users_post_body.json
- api-contract/samples/users_post_response.json
- src/main/kotlin/com/epam/brn/config/WebSecurityConfiguration.kt
- src/main/kotlin/com/epam/brn/constant/BrnParams.kt
- src/main/kotlin/com/epam/brn/constant/BrnRoles.kt
- src/main/kotlin/com/epam/brn/controller/UserDetailController.kt
- src/main/kotlin/com/epam/brn/dto/UserAccountDto.kt
- src/main/kotlin/com/epam/brn/model/Authority.kt
- src/main/kotlin/com/epam/brn/model/CustomUserDetails.kt
- src/main/kotlin/com/epam/brn/model/UserAccount.kt
- src/main/kotlin/com/epam/brn/repo/AuthorityRepository.kt
- src/main/kotlin/com/epam/brn/repo/UserAccountRepository.kt
- src/main/kotlin/com/epam/brn/service/AuthorityService.kt
- src/main/kotlin/com/epam/brn/service/BrainUpUserDetailsService.kt
- src/main/kotlin/com/epam/brn/service/InitialDataLoader.kt
- src/main/kotlin/com/epam/brn/service/UserAccountService.kt
- src/main/kotlin/com/epam/brn/service/impl/AuthorityServiceImpl.kt
- src/main/kotlin/com/epam/brn/service/impl/UserAccountServiceImpl.kt
- src/test/kotlin/com/epam/brn/controller/UserDetailControllerTest.kt
- src/test/kotlin/com/epam/brn/integration/AuthorizationAuthenticationIT.kt
- src/test/kotlin/com/epam/brn/integration/CsvLoadingTestIT.kt
- src/test/kotlin/com/epam/brn/service/UserAccountServiceTest.kt
- src/test/resources/application.properties
- src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
[EPMLABSBRN-225](https://jira.epam.com/jira/browse/EPMLABSBRN-225)
**New Api for User Management**
**Raml changes**
**Services**
**Tests**
> EPMLABSBRN-225 create auth api

- frontend-angular/package-lock.json
EPMLABSBRN-288 Fix to Correct errors in package-lock.json
Fix to Correct errors in package-lock.json
> EPMLABSBRN-288 - fixed error with package-lock.json

- .githooks/commit-msg
- .githooks/pre-commit
- .githooks/pre-push
[EPMLABSBRN-286 ](https://jira.epam.com/jira/browse/EPMLABSBRN-286 )
use nodejs as git hooks env to support windows
> EPMLABSBRN-286 - nodejs based git hooks to support windows

- api-contract/api.raml
EPMLABSBRN-290 fix raml api
done
> EPMLABSBRN-290 fix raml api

- src/main/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdvice.kt
> EPMLABSBRN-172 s3 storage

- src/main/kotlin/com/epam/brn/config/AwsConfig.kt
- src/main/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdvice.kt
- src/main/resources/application.properties
- src/test/kotlin/com/epam/brn/integration/CloudControllerAwsIT.kt
- src/test/resources/application.properties
[EPMLABSBRN-295](https://jira.epam.com/jira/browse/EPMLABSBRN-295)
**Description**: 
removed from properties aws secret key which should be read from external file
> EPMLABSBRN-295 storing cloud credentials in external file not properties

- .github/workflows/fe-composition-analysis.yml
- .github/workflows/frontend-test.yml
[EPMLABSBRN-178](https://jira.epam.com/jira/browse/EPMLABSBRN-178)
**Description**: NPM Audit scanner integration
> EPMLABSBRN-178 npm audit integration

- src/main/kotlin/com/epam/brn/csv/converter/impl/secondSeries/Exercise2SeriesConverter.kt
[EPMLABSBRN-296](https://jira.epam.com/jira/browse/EPMLABSBRN-296)
Added updating exercises while loading 2 series
> EPMLABSBRN-296 - BackEnd: update task / exercise if in new file came object with same constrain

- api-contract/api.raml
- api-contract/samples/cloud_folders.json
- src/main/kotlin/com/epam/brn/config/AwsConfig.kt
- src/main/kotlin/com/epam/brn/config/GoogleCloudConfig.kt
- src/main/kotlin/com/epam/brn/config/WebSecurityBasicConfiguration.kt
- src/main/kotlin/com/epam/brn/constant/BrnPath.kt
- src/main/kotlin/com/epam/brn/controller/CloudController.kt
- src/main/kotlin/com/epam/brn/service/CloudService.kt
- src/main/kotlin/com/epam/brn/service/impl/AwsCloudService.kt
- src/main/kotlin/com/epam/brn/service/impl/GoogleCloudService.kt
- src/main/resources/application.properties
- src/test/kotlin/com/epam/brn/integration/CloudControllerAwsIT.kt
- src/test/kotlin/com/epam/brn/integration/CloudControllerGoogleIT.kt
- src/test/kotlin/com/epam/brn/integration/configuration/AwsTestConfig.kt
- src/test/kotlin/com/epam/brn/service/impl/AwsCloudServiceTest.kt
- src/test/kotlin/com/epam/brn/service/impl/GoogleCloudServiceTest.kt
- src/test/resources/application.properties
[EPMLABSBRN-298](https://jira.epam.com/jira/browse/EPMLABSBRN-298)
**Description**: BackEnd: make a get end-point which would return folders from s3
> Epmlabsbrn 298 make a get end-point which would return folders from aws s3

- frontend/app/components/task-player/sentence/component.js
- frontend/app/components/task-player/sentence/template.hbs
- frontend/app/components/task-player/words-sequences/component.js
- frontend/app/components/task-player/words-sequences/template.hbs
- frontend/app/components/text-image-button/component.js
- frontend/app/components/text-image-button/styles.css
- frontend/app/components/text-image-button/template.hbs
[EPMLABSBRN-269](https://jira.epam.com/jira/browse/EPMLABSBRN-269)
This is kinda remake of @iki6 https://github.com/Brain-up/brn/pull/322, because it's staled and has alot of side-work inside. I prefer to land it to close original task.
Smaller PRs -> Faster landing.
Details:
by default we use focus state hovering for a11y (blue)
additional borders - green/red for different asnwers
> EPMLABSBRN-269

- docker-compose-with-secret.yml
[EPMLABSBRN-299](https://jira.epam.com/jira/browse/EPMLABSBRN-299)
Added docker-compose file for run with secret of aws keys
> EPMLABSBRN-299 devops: run appl with custom props for s3

- frontend/app/components/header/component.js
- frontend/app/components/header/template.hbs
[EPMLABSBRN-319](https://jira.epam.com/jira/browse/EPMLABSBRN-319)
> EPMLABSBRN-319 logout button

- frontend/app/components/header/template.hbs
- frontend/app/components/login-form/template.hbs
- frontend/app/components/registration-form/template.hbs
- frontend/app/routes/index.js
- frontend/app/services/network.js
- frontend/app/templates/application.hbs
[EPMLABSBRN-321](https://jira.epam.com/jira/browse/EPMLABSBRN-321) Align login/registration form design
> EPMLABSBRN-321 Align login/registration form design

- src/main/kotlin/com/epam/brn/service/InitialDataLoader.kt
- src/main/kotlin/com/epam/brn/service/ResourceService.kt
- src/test/kotlin/com/epam/brn/service/impl/AuthenticationBasicServiceImplTest.kt
Epmlabsbrn 311 remove non working suppress warning annoations <eom>
> Epmlabsbrn 311 remove non working suppress warning annoations

- src/test/kotlin/com/epam/brn/controller/UserDetailControllerTest.kt
EPMLABSBRN-311 remove duplicated test case <eom>
> EPMLABSBRN-311 remove duplicated test case <eom>

- frontend/app/components/header/template.hbs
- frontend/app/components/loading-spinner/component.js
- frontend/app/components/loading-spinner/styles.css
- frontend/app/components/loading-spinner/template.hbs
- frontend/app/components/login-form/component.js
- frontend/app/components/login-form/template.hbs
- frontend/app/components/registration-form/component.js
- frontend/app/components/registration-form/template.hbs
- frontend/app/routes/group/series/exercise/task.js
- frontend/app/services/network.js
- frontend/app/templates/group/series-loading.hbs
- frontend/tests/integration/components/loading-spinner/component-test.js
[EPMLABSBRN-329](https://jira.epam.com/jira/browse/EPMLABSBRN-329)
adds loading spinner for login/registration pages and tasks list
> EPMLABSBRN-329 adds loading spinner for login/registration pages and tasks list

- .github/workflows/frontend-angular-test.yml
- Dockerfile_frontend
- frontend-angular/e2e/protractor.conf.js
- frontend-angular/karma.conf.js
- frontend-angular/package-lock.json
- frontend-angular/package.json
[EPMLABSBRN-283](https://jira.epam.com/jira/browse/EPMLABSBRN-283)
devops: add run tests for angular part of project
> EPMLABSBRN-283 devops: add run tests for angular part of project

- frontend/app/components/audio-player/component.js
- frontend/app/components/task-player/single-words/component.js
- frontend/app/utils/audio-api.js
- frontend/mirage/config.js
- frontend/tests/acceptance/task-flow/tasks-flow-test.js
- frontend/tests/integration/components/audio-player/component-test.js
- frontend/tests/unit/utils/audio-api-test.js
[EPMLABSBRN-317](https://jira.epam.com/jira/browse/EPMLABSBRN-317)
We need more control over audio playback, including channels mixing and noize generation
> EPMLABSBRN-317 WebAudio API

- src/test/kotlin/com/epam/brn/integration/AuthorizationAuthenticationIT.kt
- src/test/kotlin/com/epam/brn/integration/SeriesControllerIT.kt
- src/test/kotlin/com/epam/brn/integration/TaskControllerIT.kt
- src/test/kotlin/com/epam/brn/service/impl/AuthenticationBasicServiceImplTest.kt
This PR aimed to fix IT failures that blocks development.
Additionally there are some Sonar fixes and file format updates.
> Fix IT tests failures + Sonar issues

- frontend/app/styles/app.css
- frontend/ember-cli-build.js
- frontend/package.json
- frontend/yarn.lock
[EPMLABSBRN-369](https://jira.epam.com/jira/browse/EPMLABSBRN-369)
css bundle size reduced from 500kb to 100kb
> EPMLABSBRN-369 use purgecss

- frontend/app/components/audio-player/component.js
- frontend/app/components/task-player/component.js
- frontend/app/components/task-player/single-words/component.js
- frontend/app/components/task-player/template.hbs
- frontend/app/models/task.js
[EPMLABSBRN-371](https://jira.epam.com/jira/browse/EPMLABSBRN-371)
> EPMLABSBRN-371 - ensure tasks ordering on playback step

- frontend/app/models/exercise.js
[EPMLABSBRN-391](https://jira.epam.com/jira/browse/EPMLABSBRN-391)
> EPMLABSBRN-391 use real user id

- frontend/app/components/exercise-stats/component.js
- frontend/app/components/exercise-stats/panel/template.hbs
- frontend/app/components/exercise-stats/template.hbs
- frontend/app/components/task-player/component.js
- frontend/app/controllers/group/series/exercise.js
- frontend/app/models/exercise.js
- frontend/app/routes/group/series/exercise.js
- frontend/app/templates/group/series/exercise.hbs
- frontend/tests/acceptance/task-flow/tasks-flow-test.js
- frontend/tests/integration/components/exercise-stats/component-test.js
- frontend/tests/integration/components/exercise-stats/panel/component-test.js
[EPMLABSBRN-264](https://jira.epam.com/jira/browse/EPMLABSBRN-264)
> EPMLABSBRN-264 initial implementation

- frontend/app/components/audio-player/component.js
- frontend/app/components/task-player/component.js
- frontend/app/components/task-player/words-sequences/component.js
- frontend/app/components/text-image-button/component.js
- frontend/app/services/audio.js
> chore: fix player pics

- frontend/app/components/task-player/component.js
- frontend/app/components/task-player/single-simple-words/component.js
[EPMLABSBRN-355](https://jira.epam.com/jira/browse/EPMLABSBRN-XX)
**Description**: additional fixes for EPMLABSBRN-355
> EPMLABSBRN-355

- frontend/app/components/task-player/component.js
- frontend/app/components/task-player/sentence/component.js
- frontend/app/components/task-player/sentence/template.hbs
- frontend/app/controllers/group/series/exercise.js
- frontend/app/routes/group/series/exercise.js
follow up fix for player behavour in 3 series
> chore: fix sentence series

- frontend/app/components/task-player/sentence/styles.css
- frontend/app/styles/app.css
- frontend/app/templates/group/series/exercise.hbs
[EPMLABSBRN-289](https://jira.epam.com/jira/browse/EPMLABSBRN-289)
> EPMLABSBRN-289

- frontend/app/serializers/task.js
[EPMLABSBRN-371](https://jira.epam.com/jira/browse/EPMLABSBRN-371)
> EPMLABSBRN-371 - 4 series

- frontend/app/components/login-form/component.js
- frontend/app/components/login-form/input/component.js
- frontend/app/components/login-form/input/template.hbs
- frontend/app/components/login-form/template.hbs
- frontend/tests/integration/components/login-form/component-test.js
- frontend/tests/integration/components/login-form/input/component-test.js
[EPMLABSBRN-410](https://jira.epam.com/jira/browse/EPMLABSBRN-410)
[EPMLABSBRN-342](https://jira.epam.com/jira/browse/EPMLABSBRN-342)
> EPMLABSBRN-410 - fix whitespace handing & wrong creds message

- frontend/app/components/task-player/component.js
[EPMLABSBRN-400](https://jira.epam.com/jira/browse/EPMLABSBRN-400)
> EPMLABSBRN-400 fix play text

- src/main/kotlin/com/epam/brn/upload/csv/series1/SeriesOneRecordProcessor.kt
- src/test/kotlin/com/epam/brn/integration/CsvLoadingTestIT.kt
[EPMLABSBRN-481](https://jira.epam.com/jira/browse/EPMLABSBRN-481)
fix: return exercises 1 series with noise
> EPMLABSBRN-481 https://github.com/Brain-up/brn/pull/559

- src/main/kotlin/com/epam/brn/model/Task.kt
- src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/main/kotlin/com/epam/brn/service/TaskService.kt
- src/test/kotlin/com/epam/brn/service/ExerciseServiceTest.kt
- src/test/kotlin/com/epam/brn/service/TaskServiceTest.kt
[EPMLABSBRN-309](https://jira.epam.com/jira/browse/EPMLABSBRN-309)
add avaliabile all exercises option for admin user
> EPMLABSBRN-309 add avaliabile all exercises option for admin user

- frontend/app/models/completion-dependent.js
- frontend/app/models/exercise.js
[EPMLABSBRN-485](https://jira.epam.com/jira/browse/EPMLABSBRN-485)
> EPMLABSBRN-485 handle available flag from be for exercise

- frontend/app/components/login-form/input/template.hbs
- frontend/app/components/registration-form/component.js
- frontend/app/components/registration-form/template.hbs
- frontend/tests/integration/components/login-form/input/component-test.js
- frontend/tests/integration/components/registration-form/component-test.js
[EPMLABSBRN-408](https://jira.epam.com/jira/browse/EPMLABSBRN-408)
> EPMLABSBRN-408

- frontend/app/components/group-navigation/template.hbs
- frontend/tests/acceptance/series-availability/series-availability-test.js
- frontend/tests/acceptance/series-availability/test-suport/data-storage.js
- frontend/tests/acceptance/series-availability/test-suport/page-object.js
[EPMLABSBRN-154](https://jira.epam.com/jira/browse/EPMLABSBRN-154)
> EPMLABSBRN-154

- frontend/app/components/task-player/sentence/styles.css
- frontend/app/components/task-player/words-sequences/styles.css
- frontend/app/components/task-player/words-sequences/template.hbs
- frontend/app/components/text-image-button/component.js
- frontend/app/components/text-image-button/styles.css
- frontend/app/components/text-image-button/template.hbs
- frontend/app/styles/app.css
[EPMLABSBRN-490](https://jira.epam.com/jira/browse/EPMLABSBRN-490)
> EPMLABSBRN-490 fix grid size for answers and add text

- frontend/app/components/task-player/sentence/component.js
- frontend/app/components/task-player/single-simple-words/component.js
- frontend/app/components/task-player/words-sequences/component.js
[EPMLABSBRN-326](https://jira.epam.com/jira/browse/EPMLABSBRN-326)
> EPMLABSBRN-326

- frontend/app/components/loading-spinner/template.hbs
- frontend/app/components/task-player/sentence/styles.css
- frontend/app/components/task-player/sentence/template.hbs
- frontend/app/components/task-player/single-simple-words/template.hbs
- frontend/app/components/task-player/template.hbs
- frontend/app/components/task-player/words-sequences/styles.css
- frontend/app/components/task-player/words-sequences/template.hbs
- frontend/app/styles/app.css
- frontend/app/templates/group.hbs
- frontend/app/templates/group/series/exercise.hbs
[EPMLABSBRN-422](https://jira.epam.com/jira/browse/EPMLABSBRN-422)
> EPMLABSBRN-422/fix-styles

- frontend/app/components/task-player/component.js
[EPMLABSBRN-422](https://jira.epam.com/jira/browse/EPMLABSBRN-422)
> EPMLABSBRN-422

- frontend/app/components/answer-correctness-widget/styles.css
- frontend/app/components/audio-player/styles.css
- frontend/app/components/exercise-type/styles.css
- frontend/app/components/footer/styles.css
- frontend/app/components/group-navigation/styles.css
- frontend/app/components/header/styles.css
- frontend/app/components/loading-spinner/styles.css
- frontend/app/components/robot/styles.css
- frontend/app/components/series-navigation/styles.css
- frontend/app/components/start-task-button/styles.css
- frontend/app/components/task-player/sentence/styles.css
- frontend/app/components/task-player/styles.css
- frontend/app/components/task-player/words-sequences/styles.css
- frontend/app/components/text-image-button/styles.css
- frontend/app/components/timer/styles.css
> style: purgecss

- frontend/app/components/progress-indicator/component.js
- frontend/app/styles/tailwind.js
- frontend/tests/integration/components/progress-indicator/component-test.js
> fix: incorrect left items counting

- frontend/app/components/breadcrumbs/styles.css
- frontend/app/components/image-display-block/styles.css
- frontend/app/components/progress-bar-circle/styles.css
- frontend/app/components/progress-indicator/styles.css
> style: purgecss fixes

- frontend/app/components/answer-correctness-widget/styles.css
- frontend/app/components/answer-correctness-widget/template.hbs
- frontend/app/components/exercise-stats/component.js
- frontend/app/components/exercise-stats/panel/template.hbs
- frontend/app/components/exercise-stats/template.hbs
- frontend/app/components/registration-form/template.hbs
- frontend/app/styles/app.css
- frontend/app/styles/tailwind.js
- frontend/app/templates/group/series/exercise.hbs
- frontend/public/ui/statistics-background.svg
- frontend/tests/integration/components/exercise-stats/component-test.js
- frontend/tests/integration/components/exercise-stats/panel/component-test.js
- frontend/translations/en-us.yaml
- frontend/translations/ru-ru.yaml
> redesign statistics page

- frontend/app/components/login-form/input/component.js
- frontend/app/components/login-form/input/template.hbs
- frontend/app/components/login-form/template.hbs
- frontend/app/components/registration-form/component.js
- frontend/app/components/registration-form/template.hbs
- frontend/translations/en-us.yaml
- frontend/translations/ru-ru.yaml
[EPMLABSBRN-341](https://jira.epam.com/jira/browse/EPMLABSBRN-341)
> EPMLABSBRN-341: fix duplicate email error

- frontend/app/routes/group/series/exercise/task.js
[EPMLABSBRN-186](https://jira.epam.com/jira/browse/EPMLABSBRN-186)
> EPMLABSBRN-186: fix double loading

- frontend/app/components/audio-player/styles.css
- frontend/app/components/audio-player/template.hbs
- frontend/app/components/task-player/sentence/template.hbs
- frontend/app/components/task-player/single-simple-words/template.hbs
- frontend/app/components/task-player/single-words/template.hbs
- frontend/app/components/task-player/words-sequences/template.hbs
[EPMLABSBRN-402](https://jira.epam.com/jira/browse/EPMLABSBRN-402)
> EPMLABSBRN-402: hide play button for non task modes

- frontend/app/components/series-navigation/template.hbs
[EPMLABSBRN-530](https://jira.epam.com/jira/browse/EPMLABSBRN-530)
> EPMLABSBRN-530 - split list of items by chunks of 3

- src/main/kotlin/com/epam/brn/model/Resource.kt
- src/main/kotlin/com/epam/brn/service/ResourceCreationService.kt
- src/main/kotlin/com/epam/brn/upload/csv/series1/SeriesOneRecordMappingIteratorProvider.kt
- src/main/kotlin/com/epam/brn/upload/csv/series1/SeriesOneRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/series2/SeriesTwoRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/series3/SeriesThreeRecordProcessor.kt
- src/test/kotlin/com/epam/brn/service/ResourceCreationServiceTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/CsvParserTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/series1/SeriesOneRecordProcessorTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/series2/SeriesTwoRecordProcessorTest.kt
[EPMLABSBRN-525](https://jira.epam.com/jira/browse/EPMLABSBRN-525)
generate files with words for 1, 2 series
> EPMLABSBRN-525 generate files with words for 1, 2 series

- frontend/app/components/exercise-stats/component.js
- frontend/app/components/login-form/component.js
- frontend/app/components/registration-form/component.js
- frontend/translations/en-us.yaml
- frontend/translations/ru-ru.yaml
[EPMLABSBRN-542](https://jira.epam.com/jira/browse/EPMLABSBRN-542)
> EPMLABSBRN-542: improve registration logic localization

- src/main/kotlin/com/epam/brn/service/AudioFilesGenerationService.kt
- src/main/resources/application.properties
- src/test/kotlin/com/epam/brn/integration/AudioFilesGenerationServiceIT.kt
- src/test/resources/application.properties
[EPMLABSBRN-527](https://jira.epam.com/jira/browse/EPMLABSBRN-527)
> EPMLABSBRN-527 add folder for generated audio files as parameter

- src/main/resources/application.properties
[EPMLABSBRN-545](https://jira.epam.com/jira/browse/EPMLABSBRN-545)
> EPMLABSBRN-545 add generated audio files

- .github/workflows/docker-build-push-redeploy.yml
[EPMLABSBRN-559](https://jira.epam.com/jira/browse/EPMLABSBRN-559)
Currently variable s3_key looks like didn't work as needed, need to fix it
- added base64 decode, and encrypted with base64 our key file
> EPMLABSBRN-559: devops: fix issue with s3 key

- src/main/kotlin/com/epam/brn/auth/AuthenticationBasicServiceImpl.kt
- src/test/kotlin/com/epam/brn/service/impl/AuthenticationBasicServiceImplTest.kt
[EPMLABSBRN-363](https://jira.epam.com/jira/browse/EPMLABSBRN-363)
> EPMLABSBRN-363 solving case-sens in email

- api-contract/samples/exercise_for_1_series.json
- api-contract/samples/exercises_for_1_series.json
- src/main/kotlin/com/epam/brn/dto/ExerciseDto.kt
- src/main/kotlin/com/epam/brn/dto/NoiseDto.kt
- src/main/kotlin/com/epam/brn/model/Exercise.kt
- src/test/kotlin/com/epam/brn/controller/ExerciseControllerTest.kt
- src/test/kotlin/com/epam/brn/service/ExerciseServiceTest.kt
[EPMLABSBRN-554](https://jira.epam.com/jira/browse/EPMLABSBRN-554)
add noise dto to ExerciseDto
> EPMLABSBRN-554 Add noise dto to ExerciseDto

- frontend/app/models/exercise.js
- frontend/app/services/audio.js
- frontend/app/utils/audio-api.js
- frontend/yarn.lock
[EPMLABSBRN-565](https://jira.epam.com/jira/browse/EPMLABSBRN-565)
> EPMLABSBRN-565: align noize level

- frontend/app/components/series-navigation/styles.css
- frontend/app/components/series-navigation/template.hbs
- frontend/app/templates/group/series/exercise.hbs
- frontend/package.json
- frontend/tests/acceptance/exercise-availability/exercises-availability-test.js
- frontend/tests/integration/components/timer/component-test.js
- frontend/yarn.lock
[EPMLABSBRN-571](https://jira.epam.com/jira/browse/EPMLABSBRN-571)
> EPMLABSBRN-571: implement ordering

- frontend/app/components/task-player/component.js
- frontend/app/services/audio.js
[EPMLABSBRN-573](https://jira.epam.com/jira/browse/EPMLABSBRN-573)
> EPMLABSBRN-573

- frontend/app/components/task-player/sentence/component.js
- frontend/app/models/exercise.js
- frontend/app/services/audio.js
- frontend/app/services/network.js
[EPMLABSBRN-850](https://jira.epam.com/jira/browse/EPMLABSBRN-580)
Added ability to play noise url's
> support for Noise URL

- src/main/kotlin/com/epam/brn/dto/ResourceDto.kt
- src/main/kotlin/com/epam/brn/model/Task.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/main/kotlin/com/epam/brn/service/TaskService.kt
- src/main/kotlin/com/epam/brn/service/UrlConversionService.kt
- src/main/kotlin/com/epam/brn/upload/csv/series1/SeriesOneRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/series2/SeriesTwoRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/series3/SeriesThreeRecordProcessor.kt
- src/main/resources/application.properties
- src/test/kotlin/com/epam/brn/service/ExerciseServiceTest.kt
- src/test/kotlin/com/epam/brn/service/TaskServiceTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/series1/SeriesOneRecordProcessorTest.kt
- src/test/resources/application.properties
[EPMLABSBRN-578](https://jira.epam.com/jira/browse/EPMLABSBRN-578)
Back-end: store audio files with md5Hex hash(word) as file name
> 578 Back-end: store audio files with md5Hex hash(word) as file name

- frontend/app/services/audio.js
- frontend/app/utils/file-url.js
[EPMLABSBRN-584](https://jira.epam.com/jira/browse/EPMLABSBRN-584)
Since now we store audio files in amazon, we have to use absolute paths for resolution.
> EPMLABSBRN-584

- frontend/app/components/series-navigation/styles.css
- frontend/app/components/series-navigation/template.hbs
- frontend/app/components/task-player/component.js
- frontend/app/components/ui/icon/check.hbs
- frontend/translations/ru-ru.yaml
> feature: reduced task size, and not it has 5 in a line, instead of a 3

- frontend/app/components/audio-player/component.ts
- frontend/app/components/task-player/component.ts
- frontend/app/components/task-player/signal/index.hbs
- frontend/app/components/task-player/signal/index.js
- frontend/app/components/task-player/signal/index.ts
- frontend/app/models/exercise.ts
- frontend/app/models/signal.js
- frontend/app/models/task/signal.js
- frontend/app/serializers/exercise.js
- frontend/app/serializers/signal.js
- frontend/app/serializers/task/signal.js
- frontend/app/services/audio.ts
- frontend/package.json
- frontend/tests/integration/components/task-player/signal-test.js
- frontend/tests/unit/models/signal-test.js
- frontend/tests/unit/models/task/signal-test.js
- frontend/tests/unit/serializers/signal-test.js
- frontend/tests/unit/serializers/task/signal-test.js
- frontend/yarn.lock
> feat signal model

- src/main/kotlin/com/epam/brn/dto/StudyHistoryDto.kt
- src/main/kotlin/com/epam/brn/model/StudyHistory.kt
- src/main/kotlin/com/epam/brn/repo/ExerciseRepository.kt
- src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/main/kotlin/com/epam/brn/service/InitialDataLoader.kt
- src/main/kotlin/com/epam/brn/service/StudyHistoryService.kt
- src/main/resources/application.properties
- src/test/kotlin/com/epam/brn/service/ExerciseServiceTest.kt
- src/test/resources/application.properties
[EPMLABSBRN-579](https://jira.epam.com/jira/browse/EPMLABSBRN-579)
prepare to availably calculation, fix bug
> Epmbrn 579

- frontend/app/components/audio-player/component.ts
- frontend/app/components/exercise-group.hbs
- frontend/app/components/exercise-stats/component.ts
- frontend/app/components/exercise-stats/panel/template.hbs
- frontend/app/components/exercise-stats/template.hbs
- frontend/app/components/task-player/sentence/component.ts
- frontend/app/components/task-player/signal/index.ts
- frontend/app/components/task-player/single-simple-words/component.ts
- frontend/app/components/task-player/single-words/component.ts
- frontend/app/components/task-player/words-sequences/component.ts
- frontend/app/controllers/group/series.js
- frontend/app/models/exercise.ts
- frontend/app/utils/audio-api.ts
- frontend/tests/integration/components/exercise-stats/component-test.js
- frontend/translations/en-us.yaml
- frontend/translations/ru-ru.yaml
[EPMLABSBRN-628](https://jira.epam.com/jira/browse/EPMLABSBRN-628)
> EPMLABSBRN-628 fix found issues

- src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/test/kotlin/com/epam/brn/service/ExerciseServiceTest.kt
[EPMLABSBRN-579](https://jira.epam.com/jira/browse/EPMLABSBRN-579)
add calculation of availability
> EPMLABSBRN-579 add calculation of availability

- src/main/kotlin/com/epam/brn/controller/StudyHistoryController.kt
- src/main/kotlin/com/epam/brn/model/StudyHistory.kt
- src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/main/kotlin/com/epam/brn/service/StudyHistoryService.kt
- src/test/kotlin/com/epam/brn/controller/StudyHistoryControllerTest.kt
- src/test/kotlin/com/epam/brn/integration/ExercisesControllerIT.kt
- src/test/kotlin/com/epam/brn/service/ExerciseServiceTest.kt
- src/test/kotlin/com/epam/brn/service/StudyHistoryServiceTest.kt
[EPMLABSBRN-579](https://jira.epam.com/jira/browse/EPMLABSBRN-579)
add saving all study history objects into db
> EPMLABSBRN-579 add saving all study history objects into db

- src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
[EPMLABSBRN-633](https://jira.epam.com/jira/browse/EPMLABSBRN-633)
fix query
> EMPLABSBRN-633 fix query

- src/main/kotlin/com/epam/brn/service/StudyHistoryService.kt
- src/test/kotlin/com/epam/brn/service/StudyHistoryServiceTest.kt
[EPMLABSBRN-634](https://jira.epam.com/jira/browse/EPMLABSBRN-634)
save exercise  duration into db
> EPMBRNLABS-634 save exercise duration into db

- api-contract/api.raml
- src/main/kotlin/com/epam/brn/controller/StudyHistoryController.kt
- src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/main/kotlin/com/epam/brn/service/StudyHistoryService.kt
- src/test/kotlin/com/epam/brn/integration/ExercisesControllerIT.kt
- src/test/kotlin/com/epam/brn/integration/StudyHistoryIT.kt
- src/test/kotlin/com/epam/brn/service/StudyHistoryServiceTest.kt
[EPMLABSBRN-189](https://jira.epam.com/jira/browse/EPMLABSBRN-189)
add todayTimer end-point
> EPMLABSBRN-189 add todayTimer end-point

- api-contract/api.raml
- src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
- src/main/kotlin/com/epam/brn/service/StudyHistoryService.kt
- src/test/kotlin/com/epam/brn/integration/StudyHistoryIT.kt
[EPMLABSBRN-189X](https://jira.epam.com/jira/browse/EPMLABSBRN-189)
> Epmlabsbrn 189 fix get timer for user with empty history

- src/main/kotlin/com/epam/brn/service/InitialDataLoader.kt
[EPMLABSBRN-633](https://jira.epam.com/jira/browse/EPMLABSBRN-633)
fix order
> EMPLABSBRN-633 fix order

- frontend/app/adapters/application.js
- frontend/app/components/group-navigation/styles.css
- frontend/app/components/group-navigation/template.hbs
- frontend/app/components/task-player/component.ts
- frontend/app/components/task-player/phrase/index.ts
- frontend/app/models/task/phrase.ts
- frontend/app/serializers/exercise.js
- frontend/tests/integration/components/task-player/phrase-test.js
- frontend/tests/unit/models/task/phrase-test.js
> feat: phrase taks support

- api-contract/api.raml
- api-contract/samples/study_histories_dto_response.json
- api-contract/samples/users_get_response.json
- src/main/kotlin/com/epam/brn/controller/AdminController.kt
- src/main/kotlin/com/epam/brn/controller/StudyHistoryController.kt
- src/main/kotlin/com/epam/brn/controller/UserDetailController.kt
- src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
- src/main/kotlin/com/epam/brn/service/StudyHistoryService.kt
- src/main/kotlin/com/epam/brn/service/UserAccountService.kt
- src/main/kotlin/com/epam/brn/service/impl/UserAccountServiceImpl.kt
- src/test/kotlin/com/epam/brn/integration/AdminControllerIT.kt
[EPMLABSBRN-639](https://jira.epam.com/jira/browse/EPMLABSBRN-639)
create end-points returning 1. users, 2. studyHistory for choosing user for period
> EPMLABSBRN-639 create end-points returning 1. users, 2. studyHistory for choosing user for period

- frontend/app/components/exercise-stats/panel/template.hbs
> fixed sero values case for stats

- src/main/resources/application.properties
[EPMLABSBRN-575](https://jira.epam.com/jira/browse/EPMLABSBRN-575)
return flyway
> EPMLABSBRN-575 return flyway

- api-contract/api.raml
- src/main/kotlin/com/epam/brn/auth/AuthenticationBasicServiceImpl.kt
- src/main/kotlin/com/epam/brn/auth/AuthenticationService.kt
- src/main/kotlin/com/epam/brn/controller/AuthenticationController.kt
- src/main/kotlin/com/epam/brn/controller/ExerciseController.kt
- src/main/kotlin/com/epam/brn/dto/request/ExerciseRequest.kt
- src/main/kotlin/com/epam/brn/dto/request/LoginDto.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/test/kotlin/com/epam/brn/service/impl/AuthenticationBasicServiceImplTest.kt
[EPMLABSBRN-633](https://jira.epam.com/jira/browse/EPMLABSBRN-633)
add get exercises/byIds end-point
> EMPLABSBRN-633 add get exercises/byIds end-point

- README.md
- api-contract/api.raml
- src/main/kotlin/com/epam/brn/controller/ExerciseController.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
[EPMLABSBRN-633](https://jira.epam.com/jira/browse/EPMLABSBRN-633)
> Epmlabsbrn 633 fix end-point /byIds

- frontend/app/components/series-navigation/template.hbs
- frontend/app/controllers/group/series.ts
- frontend/app/controllers/group/series/exercise/task.js
- frontend/app/services/network.ts
- frontend/tests/acceptance/exercise-availability/exercises-availability-test.js
- frontend/tests/acceptance/exercise-availability/test-support/data-storage.js
- frontend/tests/acceptance/general-helpers.js
[EPMLABSBRN-658](https://jira.epam.com/jira/browse/EPMLABSBRN-658)
> EPMLABSBRN-658 fix availability

- src/main/kotlin/com/epam/brn/service/TaskService.kt
- src/test/kotlin/com/epam/brn/service/TaskServiceTest.kt
[EPMLABSBRN-663](https://jira.epam.com/jira/browse/EPMLABSBRN-663)
fix generation audio url
> EPMLABSBRN-663 fix 2,3 series (generation audio url)

- src/main/resources/application.properties
[EPMLABSBRN-668](https://jira.epam.com/jira/browse/EPMLABSBRN-668)
return fly way
> EMPLABSBRN-668 return fly way

- .github/workflows/java-ci.yml
> Decrease count of logs

- .github/workflows/java-ci.yml
- build.gradle
- src/main/kotlin/com/epam/brn/config/SwaggerConfig.kt
[EPMLABSBRN-300](https://jira.epam.com/jira/browse/EPMLABSBRN-300)
- Added SonarQube evaluation execution to java-ci GitHub action, so it will run for every commit and publish results into pull request
- Updated Jacoco configuration to avoid scanning dto and model packages which we are not going to test
- Fixed package name inconsistency for Swagger Config
- Added gradle build, test and sonarcheck on push to master to be able to monitor sonar relevant info
SonarCloud instruction is available here: https://kb.epam.com/display/EPMLABSBRN/Sonar
> EPMLABSBRN-300: test sonarqube plugin

- src/main/resources/application.properties
EPMLABSBRN fix registration error
> EPMLABSBRN fix registration error

- src/main/resources/application.properties
add series 2 content
[EPMLABSBRN-609](https://jira.epam.com/jira/browse/EPMLABSBRN-609)
> EPMLABSBRN-609 return validate

- .gitpod.yml
[EPMLABSBRN-684](https://jira.epam.com/jira/browse/EPMLABSBRN-684)
Fix folder in gitpod for prebuild functional
> Fix folder in gitpod for prebuild

- frontend/app/components/footer/styles.css
- frontend/app/components/footer/template.hbs
- frontend/translations/en-us.yaml
- frontend/translations/ru-ru.yaml
[EPMLABSBRN-682](https://jira.epam.com/jira/browse/EPMLABSBRN-682)
> contact us link

- src/main/resources/application.properties
[EPMLABSBRN-659](https://jira.epam.com/jira/browse/EPMLABSBRN-659)
return validate
> EMPLABSBRN-659 return validate

- frontend/app/components/audio-player/template.hbs
- frontend/app/components/exercise-steps/component.js
- frontend/app/components/exercise-steps/step/template.hbs
- frontend/app/components/exercise-steps/style.css
- frontend/app/components/exercise-steps/template.hbs
- frontend/app/components/task-player/phrase/index.hbs
- frontend/app/components/task-player/sentence/template.hbs
- frontend/app/components/task-player/signal/index.hbs
- frontend/app/components/task-player/single-simple-words/template.hbs
- frontend/app/components/task-player/single-words/template.hbs
- frontend/app/components/task-player/template.hbs
- frontend/app/components/task-player/words-sequences/template.hbs
- frontend/app/components/ui/bottom-container/index.hbs
- frontend/app/components/ui/bottom-container/style.css
- frontend/app/components/ui/chevron/index.hbs
- frontend/app/templates/group/series/subgroup/exercise.hbs
- frontend/tests/integration/components/ui/bottom-container-test.js
- frontend/tests/integration/components/ui/chevron-test.js
> add chevron

- src/main/kotlin/com/epam/brn/model/UserAccount.kt
- src/main/resources/application.properties
- src/main/resources/db/migration/V1__init_schema.sql
[EPMLABSBRN-783](https://jira.epam.com/jira/browse/EPMLABSBRN-783)
fix exception on registration step
> 783 fix exception on registration step

- src/main/resources/application.properties
fix exception on registration step
[EPMLABSBRN-783](https://jira.epam.com/jira/browse/EPMLABSBRN-783)
return flag as it should be for db migration
> EMPLABSBRN-783

- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/test/kotlin/com/epam/brn/service/ExerciseServiceTest.kt
[EPMLABSBRN-765](https://jira.epam.com/jira/browse/EPMLABSBRN-765)
fix availability
> EPMLABSBRN-765 fix availability

- frontend/app/components/exercise-group.hbs
- frontend/app/templates/group/series.hbs
> subgroup-buttons

- src/main/kotlin/com/epam/brn/dto/response/UserAccountDto.kt
- src/main/kotlin/com/epam/brn/model/CustomUserDetails.kt
- src/main/kotlin/com/epam/brn/model/UserAccount.kt
- src/main/resources/db/migration/V220210217_773.sql
[EPMLABSBRN-773](https://jira.epam.com/jira/browse/EPMLABSBRN-773)
change user data model
as a first step to move to firebase/cognito auth
> EPMLABSBRN-773 change user data model

- src/main/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdvice.kt
- src/test/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdviceTest.kt
[EPMLABSBRN-782](https://jira.epam.com/jira/browse/EPMLABSBRN-782)
fix wrong reported exception
> EPMLABSBRN-782 fix wrong reported exception

- .github/workflows/frontend-admin-test.yml
- .github/workflows/frontend-app-test.yml
- .github/workflows/java-ci.yml
Enabled all tests in all PR's created by any team
> Enabled all tests in all PRs

- frontend-angular/src/app/modules/admin/components/load-tasks/load-tasks.component.ts
- frontend-angular/src/app/modules/auth/auth.module.ts
- frontend-angular/src/app/modules/auth/components/login/login.component.ts
- frontend-angular/src/app/modules/auth/models/local-storage-auth-key.ts
- frontend-angular/src/app/modules/auth/models/login-success.model.ts
- frontend-angular/src/app/modules/auth/models/token.ts
- frontend-angular/src/app/modules/auth/ngrx/actions.ts
- frontend-angular/src/app/modules/auth/ngrx/effects.ts
- frontend-angular/src/app/modules/auth/ngrx/reducers.ts
- frontend-angular/src/app/modules/auth/services/session/session-token-coder.service.ts
- frontend-angular/src/app/modules/auth/services/session/session-token-mapper.service.ts
- frontend-angular/src/app/modules/auth/services/session/session-token.service.ts
- frontend-angular/src/app/modules/shared/services/basic-auth.interceptor.service.ts
[EPMLABSBRN-683](https://jira.epam.com/jira/browse/EPMLABSBRN-683)
Handle session token as to separate user/admin roles access
e.g. the admin part is available only for users with role ADMIN
> EPMLABSBRN-683: FE: Fix admin auth

- .github/workflows/docker-build-push-redeploy.yml
[EPMLABSBRN-654](https://jira.epam.com/jira/browse/EPMLABSBRN-654)
- fixed pipeline syntax
> EPMLABSBRN-654: implement SSL for brainup.site

- frontend/app/components/group-navigation/template.hbs
- frontend/app/modifiers/autofit-text.ts
- frontend/tests/integration/modifiers/autofit-text-test.js
> creepy-text-autoscale

- frontend/app/components/header-profile/styles.css
- frontend/app/components/header-profile/template.hbs
- frontend/app/router.js
- frontend/app/routes/profile.js
- frontend/app/templates/profile.hbs
> Profile subheader

- api-contract/api.raml
- api-contract/samples/exercises_with_tasks.json
- src/main/kotlin/com/epam/brn/controller/AdminController.kt
- src/main/kotlin/com/epam/brn/dto/ExerciseSignalDto.kt
- src/main/kotlin/com/epam/brn/dto/ExerciseWithTasksDto.kt
- src/main/kotlin/com/epam/brn/dto/GeneralTaskDto.kt
- src/main/kotlin/com/epam/brn/dto/SignalTaskDto.kt
- src/main/kotlin/com/epam/brn/model/Exercise.kt
- src/main/kotlin/com/epam/brn/model/Signal.kt
- src/main/kotlin/com/epam/brn/model/Task.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/test/kotlin/com/epam/brn/controller/LoadFilesControllerTest.kt
- src/test/kotlin/com/epam/brn/service/ExerciseServiceTest.kt
[EPMLABSBRN-826](https://jira.epam.com/jira/browse/EPMLABSBRN-826)
add /admin/exercises end-point
> EPMLABSBRN-826 add /admin/exercises end-point

- api-contract/api.raml
- api-contract/samples/user_with_analytics_get_response.json
- src/main/kotlin/com/epam/brn/controller/AdminController.kt
- src/main/kotlin/com/epam/brn/dto/response/UserWithAnalyticsDto.kt
- src/main/kotlin/com/epam/brn/model/UserAccount.kt
- src/main/kotlin/com/epam/brn/service/UserAccountService.kt
- src/main/kotlin/com/epam/brn/service/impl/UserAccountServiceImpl.kt
[EPMLABSBRN-824](https://jira.epam.com/jira/browse/EPMLABSBRN-824)
redesign /admin/users end-point
> EPMLABSBRN-824 redesign /admin/users end-point

- frontend-angular/src/app/modules/admin/modules/statistics/components/statistics-info-dialog/statistics-info-dialog.component.html
- frontend-angular/src/app/modules/shared/services/svg-icons-registrar.service.ts
[EPMLABSBRN-1911](https://github.com/Brain-up/brn/issues/1911)
> EPMLABSBRN-1911- fixed path to static resources

- frontend-angular/angular.json
- frontend-angular/src/app/modules/admin/components/home/home.component.html
- frontend-angular/src/app/modules/admin/components/home/home.component.spec.ts
- frontend-angular/src/app/modules/admin/components/home/home.component.ts
- frontend-angular/src/app/modules/auth/components/login/login.component.ts
- frontend-angular/src/app/modules/auth/ngrx/effects.ts
- frontend-angular/src/app/modules/shared/components/upload-file/upload-file.component.ts
- frontend-angular/src/app/modules/shared/constants/time-constants.ts
[EPMLABSBRN-1931](https://github.com/Brain-up/brn/issues/1931)
> EPMLABSBRN-1931 - migrated all components to onPush strategy

- frontend/package.json
- frontend/yarn.lock
fixes https://github.com/Brain-up/brn/issues/1957
> updated merge version resolution

- .github/workflows/certbot-update-cert.yml
- README.md
- default_with_tls.conf
- docker-compose-run.yml
- Removal of audibly.ru domain from certificate request, as this domain already expired and brainup.site will be used instead
- Also fixed certificate renewal process to not produce many containers like 
```
10d8b7140c9c        67cfe9e9c63f                           "certbot renew"          8 weeks ago         Exited (0) 8 weeks ago                                               brn_certbot_run_478f857850f4
65df9924358d        67cfe9e9c63f                           "certbot renew"          8 weeks ago         Exited (0) 8 weeks ago                                               brn_certbot_run_3494a2157435
7b455f12a700        67cfe9e9c63f                           "certbot renew"          8 weeks ago         Exited (0) 8 weeks ago …
```
> [DevOps] Remove audiby.ru domain from certificate request

- src/main/resources/application.properties
Fix the flyway issue when unordered migration committed
Currently we have error during start of backend service:
```shell
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-05-12 07:44:36.933 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is java.lang.reflect.InvocationTargetException
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBe …
```
> [DevOps] Fix issue with flyway migration not applied

- frontend-angular/angular.json
- frontend-angular/custom-webpack-config.ts
- frontend-angular/package-lock.json
- frontend-angular/package.json
- frontend-angular/src/app/modules/root/interceptors/exceptions.interceptor.ts
- frontend-angular/src/app/modules/root/root.module.ts
- frontend-angular/src/assets/i18n/en.json
- frontend-angular/src/assets/i18n/ru.json
- frontend-angular/src/index-transform.ts
- frontend-angular/src/index.html
- frontend-angular/tsconfig.app.json
- frontend-angular/tsconfig.spec.json
[EPMLABSBRN-1964](https://github.com/Brain-up/brn/issues/1964)
> EPMLABSBRN-1964 added caching reset

- frontend/app/components/header/template.hbs
- frontend/app/components/profile/style.css
- frontend/app/components/profile/template.hbs
- frontend/app/components/series-navigation/template.hbs
- frontend/app/components/ui/avatars/index.hbs
- frontend/app/components/ui/avatars/style.css
- frontend/app/styles/tailwind.js
> fixed modal scroll

- .gitpod.yml
- frontend-angular/angular.json
- frontend-angular/package.json
resolves https://github.com/Brain-up/brn/issues/1980
> proxy-for-admin-in-gitpod

- frontend/app/components/series-navigation/template.hbs
- frontend/app/components/ui/avatars/index.hbs
- frontend/package.json
[EPMLABSBRN-867](https://jira.epam.com/jira/browse/EPMLABSBRN-867)
* Fix HTML class attribute sorting in hbs.
* Fix Yarn Audit Errors (Add resolution of transitive dependencies)
> EPMLABSBRN-867: Fix Frontend test FAILED

- README.md
- frontend-angular/README.md
- frontend-angular/src/app/modules/auth/models/login.ts
- frontend-angular/src/app/modules/root/models/auth-token.ts
- frontend-angular/src/app/modules/shared/helpers/seconds-to.ts
[EPMLABSBRN-1998](https://github.com/Brain-up/brn/issues/1998)
> [Admin panel] Edit README

- .github/workflows/certbot-update-cert.yml
- default_with_tls.conf
[EPMLABSBRN-877](https://jira.epam.com/jira/browse/EPMLABSBRN-877)
After removal of audibly.ru domain name we faced with issues during certificate renewal
And also to be able to handle certificate renewal requests via 443 port, added section to nginx conf
> EPMLABSBRN-877: [DevOps] Fix letsencrypt certificate renewal

- build.gradle
- gradle.properties
EPMLABSBRN-880 https://jira.epam.com/jira/browse/EPMLABSBRN-880#
Import Kotest
> EPMLABSBRN-880: BE: make assertions in unit tests in one style

- .github/workflows/java-ci.yml
Added information in MR tests about gradle unit and integration tests.
It will add comment in MR, such as:
> Added publishing gradle test results

- src/main/kotlin/com/epam/brn/upload/csv/audiometrySpeech/LopotkoRecord.kt
- src/main/kotlin/com/epam/brn/upload/csv/audiometrySpeech/LopotkoRecordMappingIteratorProvider.kt
- src/main/kotlin/com/epam/brn/upload/csv/audiometrySpeech/LopotkoRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesMatrix/SeriesMatrixRecord.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesMatrix/SeriesMatrixRecordMappingIteratorProvider.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesMatrix/SeriesMatrixRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesPhrases/SeriesPhrasesRecord.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesPhrases/SeriesPhrasesRecordMappingIteratorProvider.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesPhrases/SeriesPhrasesRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesWords/SeriesWordsRecord.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesWords/SeriesWordsRecordMappingIteratorProvider.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesWords/SeriesWordsRecordProcessor.kt
- src/test/kotlin/com/epam/brn/upload/csv/CsvParserTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/lopotko/LopotkoProcessorTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/seriesMatrix/SeriesMatrixRecordProcessorTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/seriesWords/SeriesWordsRecordProcessorTest.kt
[EPMLABSBRN-851](https://jira.epam.com/jira/browse/EPMLABSBRN-j851)
refactor names in upload folder
> 851 refactor names in upload folder

- frontend/app/models/subgroup.ts
resolves: https://github.com/Brain-up/brn/issues/2048
> feat: update image paths for subgroups

- src/main/resources/application.properties
> EPMLABSBRN-000 fix deploy

- api-contract/api.raml
- api-contract/samples/exercise_for_frequency_words_series.json
- api-contract/samples/task_by_id_for_frequency_words_series.json
- src/main/kotlin/com/epam/brn/model/Task.kt
- src/main/kotlin/com/epam/brn/service/TaskService.kt
- src/test/kotlin/com/epam/brn/service/TaskServiceTest.kt
[EPMLABSBRN-883](https://jira.epam.com/jira/browse/EPMLABSBRN-883)
api for frequency series
> EPMLABSBRN-883 api for frequency series

- src/main/kotlin/com/epam/brn/service/statistic/progress/status/impl/StudyHistoriesProgressStatusManager.kt
- src/main/kotlin/com/epam/brn/service/statistic/progress/status/impl/retriever/WeekExercisingStatusRetriever.kt
[EPMLABSBRN-000](https://jira.epam.com/jira/browse/EPMLABSBRN-000)
fix npe
> EPMLABSBRN-000 fix npe

- frontend/app/adapters/user-weekly-statistics.ts
- frontend/app/adapters/user-yearly-statistics.ts
- frontend/app/components/statistics/component.ts
- frontend/app/components/statistics/month-time-track/component.ts
- frontend/app/components/statistics/month-time-track/template.hbs
- frontend/app/components/statistics/template.hbs
- frontend/app/components/statistics/week-time-track/component.ts
- frontend/app/controllers/profile/statistics.ts
- frontend/app/models/user-weekly-statistics.ts
- frontend/app/models/user-yearly-statistics.ts
- frontend/app/routes/profile/statistics.ts
- frontend/app/serializers/application.ts
- frontend/app/serializers/user-weekly-statistics.ts
- frontend/app/serializers/user-yearly-statistics.ts
- frontend/app/services/network.ts
- frontend/app/templates/profile/statistics.hbs
- frontend/app/transforms/full-date.ts
- frontend/tests/integration/components/statistics/component-test.js
- frontend/tests/integration/components/statistics/month-time-track-item/component-test.ts
- frontend/tests/integration/components/statistics/month-time-track/component-test.ts
- frontend/tests/integration/components/statistics/week-time-track/component-test.ts
- frontend/tests/unit/adapters/user-weekly-statistics-test.js
- frontend/tests/unit/adapters/user-yearly-statistics-test.js
- frontend/tests/unit/controllers/profile/statistics-test.js
- frontend/tests/unit/services/network-test.js
- frontend/tests/unit/transforms/full-date-test.js
[#2030 ] [frontend] Backport admin statistics to client app
* using serializers/adapters for parsing statistics data
* fix tests accordingly
> [frontend] #2030 ember-way for statistics loading logic

- build.gradle
- gradle.properties
- src/test/kotlin/com/epam/brn/auth/AuthorityServiceImplTest.kt
- src/test/kotlin/com/epam/brn/controller/AudioControllerTest.kt
- src/test/kotlin/com/epam/brn/controller/CloudControllerTest.kt
- src/test/kotlin/com/epam/brn/controller/UserStatisticControllerTest.kt
- src/test/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdviceTest.kt
- src/test/kotlin/com/epam/brn/service/ExerciseServiceTest.kt
- src/test/kotlin/com/epam/brn/service/TaskServiceTest.kt
- src/test/kotlin/com/epam/brn/service/UrlConversionServiceTest.kt
- src/test/kotlin/com/epam/brn/service/UserAccountServiceTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/group/GroupRecordProcessorTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/series/SeriesGenericRecordProcessorTest.kt
[EPMLABSBRN-895](https://jira.epam.com/jira/browse/EPMLABSBRN-895)
Removed all mentions and uses of mockito library and changed mocking in tests to MockK
> Removed dependencies of mockito and changed implementation of tests to MockK

- src/main/kotlin/com/epam/brn/config/WebSecurityBasicConfiguration.kt
- src/main/kotlin/com/epam/brn/model/Headphones.kt
- src/main/resources/db/migration/V220210816_900.sql
- src/test/kotlin/com/epam/brn/integration/UserDetailsControllerIT.kt
[EPMLABSBRN-900](https://jira.epam.com/jira/browse/EPMLABSBRN-900)
- fix for the current api
- added new constraint for headphones table
> EPMLABSBRN-900 - BE: fix bug post headphones for current user: 403

- frontend/app/adapters/headphone.ts
- frontend/app/models/headphone.ts
- frontend/app/serializers/headphone.ts
- frontend/tests/unit/adapters/headphone-test.js
- frontend/tests/unit/models/headphone-test.js
- frontend/tests/unit/serializers/headphone-test.js
related to: https://github.com/Brain-up/brn/issues/2065
> headphone model for frontend

- src/main/resources/db/migration/V220210805_843.sql
- src/main/resources/db/migration/V220210914_906.sql
Realated issue https://github.com/Brain-up/brn/issues/2086
> EPAMLABSBRN-843 fixing it tests

- api-contract/samples/user_with_analytics_get_response.json
- frontend-angular/src/app/modules/admin/models/user.ts
- frontend-angular/src/app/modules/admin/modules/users/components/users-table/users-table.component.ts
- frontend-angular/src/app/modules/admin/modules/users/users.module.ts
- frontend-angular/src/app/modules/admin/services/api/admin-api.service.fake.ts
- frontend-angular/src/app/modules/admin/services/api/admin-api.service.ts
- src/main/kotlin/com/epam/brn/controller/AdminController.kt
- src/main/kotlin/com/epam/brn/dto/response/UserWithAnalyticsResponse.kt
- src/main/kotlin/com/epam/brn/service/UserAccountService.kt
- src/main/kotlin/com/epam/brn/service/UserAnalyticsService.kt
- src/main/kotlin/com/epam/brn/service/impl/UserAccountServiceImpl.kt
- src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt
- src/test/kotlin/com/epam/brn/controller/AdminControllerTest.kt
- src/test/kotlin/com/epam/brn/controller/LoadFilesControllerTest.kt
- src/test/kotlin/com/epam/brn/service/UserAccountServiceTest.kt
- src/test/kotlin/com/epam/brn/service/UserAnalyticsServiceTest.kt
EPMLABSBRN-928: https://jira.epam.com/jira/browse/EPMLABSBRN-928
EPMLABSBRN-932:
https://jira.epam.com/jira/browse/EPMLABSBRN-932
FE: Remove Fake Analytics service
BE: New service added to map analytics for every user
Unit tests
> EPMLABSBRN-928: get real data from backend instead of mock in users page 

- frontend-angular/src/app/modules/admin/modules/users/components/users-table/users-table.component.html
- frontend-angular/src/assets/i18n/en.json
- frontend-angular/src/assets/i18n/ru.json
[EPMLABSBRN-932](https://jira.epam.com/jira/browse/EPMLABSBRN-932)
Update column name on statistics table
> EPMLABSBRN-932

- frontend/app/components/task-player/single-simple-words/option.hbs
> EPMLABSBRN-967

- .github/workflows/docker-build-push-redeploy.yml
- docker-compose-run.yml
[DEV-OPS] put file into server and path to it save in variable
[EPMLABSBRN-965](https://jira.epam.com/jira/browse/EPMLABSBRN-965)
Added creation of firebase_config.json file with secret and configured to use it in `GOOGLE_APPLICATION_CREDENTIALS ` env variable
> EPMLABSBRN-965: [DevOps] firebase-config variable

- src/main/kotlin/com/epam/brn/model/UserAccount.kt
- src/main/kotlin/com/epam/brn/repo/UserAccountRepository.kt
- src/main/kotlin/com/epam/brn/service/load/FirebaseUserDataLoader.kt
- src/main/resources/db/migration/V220211101_780.sql
[EPMLABSBRN-XX](https://jira.epam.com/jira/browse/EPMLABSBRN-780)
* Fix error: IndexOutOfBoundException: move init array in cycle, and add more info to detect right user when error happens.
* Add more debug info
> EPMLABSBRN-780: BE: implement Firebase authentification

- frontend/app/adapters/application.ts
- frontend/app/authenticators/firebase.ts
- frontend/app/components/login-form/template.hbs
- frontend/app/components/task-player/single-simple-words/option.hbs
- frontend/app/components/task-player/single-simple-words/option.ts
- frontend/app/models/exercise.ts
- frontend/app/modifiers/autofit-text.ts
- frontend/app/services/audio.ts
- frontend/app/services/network.ts
- frontend/app/services/user-data.ts
- frontend/app/utils/audio-api.ts
- frontend/tests/acceptance/general-helpers.js
- frontend/tests/integration/components/registration-form/component-test.js
- frontend/tests/unit/adapters/application-test.js
this PR fixes few things:
* endpoint calls with missing access token (allowed in prev implementation of authorization)
* tests fixes
* handles images errors for some kind of questions
> chore: fix auth problems for legacy endpoints

- frontend-angular/src/app/modules/admin/admin.component.html
- frontend-angular/src/app/modules/admin/admin.component.spec.ts
- frontend-angular/src/app/modules/admin/admin.module.ts
- frontend-angular/src/app/modules/admin/modules/users/users.component.html
- frontend-angular/src/app/modules/admin/modules/users/users.component.spec.ts
- frontend-angular/src/app/modules/admin/modules/users/users.module.ts
- frontend-angular/src/app/modules/shared/pipes/pipes.module.ts
- frontend-angular/src/app/modules/shared/pipes/short-name.pipe.spec.ts
- frontend-angular/src/app/modules/shared/pipes/short-name.pipe.ts
[EPMLABSBRN-XX](https://jira.epam.com/jira/browse/EPMLABSBRN-973)
- Added "shortName" transform pipe to create avatar (or other name) initials from 'name' property.
- Added "Pipes" module for flexibility
> Feature/epmlabsbrn 973 UI use dynamic avatars on users page

- frontend/app/components/task-player/single-words/component.ts
- frontend/app/models/task/frequency-words.ts
- frontend/app/models/task/phrase.ts
- frontend/app/models/task/single-simple-words.ts
- frontend/app/models/task/words-sequences.ts
- frontend/tests/integration/components/task-player/single-simple-words/component-test.js
[EPMLABSBRN-989](https://jira.epam.com/jira/browse/EPMLABSBRN-989)
> EPMLABSBRN-989 increase shuffle complexity

- frontend/app/components/task-player/component.ts
- frontend/app/components/task-player/single-simple-words/component.ts
- frontend/app/models/exercise.ts
- frontend/app/models/task.ts
- frontend/app/models/task/words-sequences.ts
- frontend/app/services/audio.ts
- frontend/app/utils/answer-option.ts
- frontend/app/utils/audio-api.ts
- frontend/package.json
- frontend/yarn.lock
[EPMLABSBRN-372](https://jira.epam.com/jira/browse/EPMLABSBRN-372)
Reuse flag to figure out source of audio file
also, partially implements https://github.com/Brain-up/brn/issues/2150
> Epmlabsbrn 372

- frontend/app/components/task-player/single-simple-words/option.ts
- frontend/app/components/text-image-button/component.ts
- frontend/app/services/image-locator.ts
- frontend/tests/unit/services/image-locator-test.js
* unified fallback image lookup logic
> image locator  service

- frontend/app/controllers/group/series/subgroup/exercise.ts
- frontend/app/modifiers/autofit-text.ts
* fixed top-menu items autosize
* fixed completed exercise window
> fix few fe issues

- frontend/app/components/task-player/single-simple-words/template.hbs
- frontend/app/index.html
- frontend/app/routes/group/series/subgroup/exercise.ts
- frontend/app/services/image-locator.ts
> fixed size on not found images

- api-contract/samples/task_by_id_for_koroleva_series.json
- src/main/kotlin/com/epam/brn/dto/ResourceDto.kt
- src/main/kotlin/com/epam/brn/dto/response/WordsTaskResponse.kt
- src/main/kotlin/com/epam/brn/model/Task.kt
- src/main/kotlin/com/epam/brn/service/TaskService.kt
- src/main/kotlin/com/epam/brn/service/WordAnalyzingService.kt
- src/main/resources/application.properties
- src/test/kotlin/com/epam/brn/controller/TaskControllerTest.kt
- src/test/kotlin/com/epam/brn/service/TaskServiceTest.kt
- src/test/resources/application.properties
[EPMLABSBRN-1018](https://jira.epam.com/jira/browse/EPMLABSBRN-1018)
add sounds calculation
> EPMLABSBRN-1018 add sounds calculation

- api-contract/samples/task_by_id_for_1_series.json
- src/main/kotlin/com/epam/brn/service/YandexSpeechKitService.kt
- src/main/resources/initFiles/series_words_koroleva_ru.csv
- src/main/resources/initFiles/subgroups_ru.csv
[EPMLABSBRN-997](https://jira.epam.com/jira/browse/EPMLABSBRN-997)
support stress words, additional part is done in DB directly
> EPMLABSBRN-997 stress words

- src/main/kotlin/com/epam/brn/controller/AudioController.kt
- src/main/kotlin/com/epam/brn/service/WordsService.kt
- src/main/kotlin/com/epam/brn/service/YandexSpeechKitService.kt
- src/test/kotlin/com/epam/brn/service/YandexSpeechKitServiceTest.kt
[EPMLABSBRN-998](https://jira.epam.com/jira/browse/EPMLABSBRN-998)
> 998 make slower

- src/main/kotlin/com/epam/brn/service/UrlConversionService.kt
> Epmbrn: fix picture url to lower case

- frontend/app/components/header/template.hbs
- src/main/kotlin/com/epam/brn/service/UrlConversionService.kt
[EPMLABSBRN-1104](https://jira.epam.com/jira/browse/EPMLABSBRN-1104)
Add link to Telegram group to have a communication channel with our users
> EPMLABSBRN-1104: Add link to Telegram group to have a communication channel with our users

- frontend/app/services/audio.ts
expose exerciseId in audio request
[EPMLABSBRN-1112](https://jira.epam.com/jira/browse/EPMLABSBRN-1112)
> EPMLABSBRN-1112

- frontend/app/components/profile/component.ts
- frontend/app/components/profile/template.hbs
- frontend/app/components/registration-form/component.ts
- frontend/app/controllers/password-recovery.ts
- frontend/app/routes/profile/index.ts
- frontend/app/services/network.ts
- frontend/app/utils/validators.ts
- frontend/patches/async-promise-queue+1.0.5.patch
[EPMLABSBRN-656](https://jira.epam.com/jira/browse/EPMLABSBRN-656)
Implemented user profile info updates.
For later: create normal user model to use with e-data
> EPMLABSBRN-656

- src/main/resources/application.properties
[EPMLABSBRN-1113](https://jira.epam.com/jira/browse/EPMLABSBRN-1113)
> EPMLABSBRN-1113 configure project azure tts

- src/main/kotlin/com/epam/brn/controller/AudioController.kt
- src/main/kotlin/com/epam/brn/dto/AudioFileMetaData.kt
- src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/main/kotlin/com/epam/brn/service/UserAccountService.kt
- src/main/kotlin/com/epam/brn/service/UserAnalyticsService.kt
- src/main/kotlin/com/epam/brn/service/WordsService.kt
- src/main/kotlin/com/epam/brn/service/YandexSpeechKitService.kt
- src/main/kotlin/com/epam/brn/service/azure/tts/AzureTextToSpeechService.kt
- src/main/kotlin/com/epam/brn/service/impl/UserAccountServiceImpl.kt
- src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt
- src/test/kotlin/com/epam/brn/controller/AudioControllerTest.kt
- src/test/kotlin/com/epam/brn/service/UserAnalyticsServiceTest.kt
- src/test/kotlin/com/epam/brn/service/azure/tts/AzureTextToSpeechServiceTest.kt
[EPMLABSBRN-1103](https://jira.epam.com/jira/browse/EPMLABSBRN-1103)
**Description**: adaptation algorithm
> EPMLABSBRN-1103 adaptation algorithm

- .github/workflows/certbot-update-cert.yml
[EPMLABSBRN-1120](https://jira.epam.com/jira/browse/EPMLABSBRN-1120)
Added restart front after update of TLS certificate process
> EPMLABSBRN-1120: DEVOPS: restart front after update TLS certificate

- api-contract/samples/user_with_analytics_get_response.json
- frontend-angular/src/app/modules/admin/models/user.model.ts
- frontend-angular/src/app/modules/admin/modules/users/users.component.html
- frontend-angular/src/app/modules/admin/modules/users/users.component.spec.ts
- frontend-angular/src/app/modules/admin/modules/users/users.component.ts
- frontend-angular/src/app/modules/admin/services/api/admin-api.service.fake.ts
- frontend-angular/src/assets/i18n/en.json
- frontend-angular/src/assets/i18n/ru.json
- src/main/kotlin/com/epam/brn/dto/response/UserWithAnalyticsResponse.kt
- src/main/kotlin/com/epam/brn/model/projection/FirstLastStudyView.kt
- src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
- src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt
- src/test/kotlin/com/epam/brn/service/UserAnalyticsServiceTest.kt
PR for #2235 
Replace mocks for workDayByLastMonth, firstDone, and lastDone with real data
> 2235 analytic fields

- frontend/app/components/exercise-study-config/index.hbs
- frontend/app/components/exercise-study-config/index.ts
- frontend/app/components/image-display-block/component.ts
- frontend/app/components/task-player/single-simple-words/option.hbs
- frontend/app/components/task-player/single-simple-words/option.ts
- frontend/app/components/task-player/template.hbs
- frontend/app/components/text-image-button/component.ts
- frontend/app/services/study-config.ts
- frontend/app/templates/group/series/subgroup/exercise.hbs
- frontend/config/icons.js
- frontend/package.json
- frontend/tests/acceptance/task-flow/tasks-flow-test.js
- frontend/tests/integration/components/exercise-study-config-test.js
- frontend/tests/unit/services/study-config-test.js
Implements #2228
Button added near playback timer
> feat: ability to disable pictures

- src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
> #2237 BE: fix variable names in SQL query for first and last study

- src/main/kotlin/com/epam/brn/service/UrlConversionService.kt
- src/main/resources/application.properties
- src/test/kotlin/com/epam/brn/service/UrlConversionServiceTest.kt
- src/test/resources/application.properties
> #2241 BE: prepare correct url for task picture

- src/main/kotlin/com/epam/brn/service/UrlConversionService.kt
- src/main/resources/application.properties
- src/test/kotlin/com/epam/brn/service/UrlConversionServiceTest.kt
- src/test/resources/application.properties
> Revert "#2241 BE: prepare correct url for task picture"

- src/main/kotlin/com/epam/brn/dto/response/UserWithAnalyticsResponse.kt
> 2256 prepare mock fields for UI part

- frontend-angular/src/app/modules/admin/modules/users/modules/statistics/components/daily-time-table/daily-time-table.component.ts
- frontend-angular/src/app/modules/admin/modules/users/modules/statistics/components/week-time-track/week-time-track.component.spec.ts
- frontend-angular/src/app/modules/admin/modules/users/modules/statistics/components/week-time-track/week-time-track.component.ts
Fixed bug: day wasn't set.
Added tests for this bug
> #2261: [UI Admin] Fix statistic values in table

- frontend-angular/src/app/modules/admin/models/user.model.ts
- frontend-angular/src/app/modules/admin/modules/users/users.component.html
- frontend-angular/src/app/modules/admin/modules/users/users.component.ts
- frontend-angular/src/assets/i18n/en.json
- frontend-angular/src/assets/i18n/ru.json
Add "Spent time" and "Done exercises" columns, add *ngIf conditions
> EPMLABSBRN-1123 UI: Add "Spent time" and "Done exercises" columns

- src/main/kotlin/com/epam/brn/dto/ResourceDto.kt
- src/main/kotlin/com/epam/brn/service/TaskService.kt
- src/main/kotlin/com/epam/brn/service/UrlConversionService.kt
- src/main/kotlin/com/epam/brn/service/cloud/AwsCloudService.kt
- src/main/kotlin/com/epam/brn/service/cloud/CloudService.kt
- src/main/kotlin/com/epam/brn/service/cloud/GoogleCloudService.kt
- src/main/resources/application.properties
- src/test/kotlin/com/epam/brn/service/TaskServiceTest.kt
- src/test/kotlin/com/epam/brn/service/UrlConversionServiceTest.kt
- src/test/resources/application.properties
> 2241picture url

- src/main/kotlin/com/epam/brn/dto/ResourceDto.kt
- src/main/kotlin/com/epam/brn/service/TaskService.kt
- src/main/kotlin/com/epam/brn/service/UrlConversionService.kt
- src/main/kotlin/com/epam/brn/service/cloud/AwsCloudService.kt
- src/main/kotlin/com/epam/brn/service/cloud/CloudService.kt
- src/main/kotlin/com/epam/brn/service/cloud/GoogleCloudService.kt
- src/main/resources/application.properties
- src/test/kotlin/com/epam/brn/service/TaskServiceTest.kt
- src/test/kotlin/com/epam/brn/service/UrlConversionServiceTest.kt
- src/test/resources/application.properties
> Revert "2241picture url"

- src/main/kotlin/com/epam/brn/dto/ResourceDto.kt
- src/main/kotlin/com/epam/brn/service/TaskService.kt
- src/main/kotlin/com/epam/brn/service/UrlConversionService.kt
- src/main/kotlin/com/epam/brn/service/cloud/AwsCloudService.kt
- src/main/kotlin/com/epam/brn/service/cloud/CloudService.kt
- src/main/kotlin/com/epam/brn/service/cloud/GoogleCloudService.kt
- src/main/resources/application.properties
- src/test/kotlin/com/epam/brn/service/TaskServiceTest.kt
- src/test/kotlin/com/epam/brn/service/UrlConversionServiceTest.kt
- src/test/resources/application.properties
> #2241 BE: fix picture url creation

- frontend/app/components/exercise-group.hbs
- frontend/app/components/exercise-group.ts
- frontend/app/components/group-navigation/template.hbs
- frontend/app/components/subgroup-navigation/index.hbs
- frontend/app/components/ui/tab-button/index.hbs
- frontend/app/templates/groups.hbs
resolves: https://github.com/Brain-up/brn/issues/2268
> Add tooltips to button components

- api-contract/api.raml
- frontend/app/adapters/user-weekly-statistics.ts
- frontend/app/adapters/user-yearly-statistics.ts
- frontend/app/utils/custom-timeout.js
- frontend/mirage/config.js
- frontend/tests/acceptance/task-flow/tasks-flow-test.js
- frontend/tests/integration/components/statistics/component-test.js
- src/main/kotlin/com/epam/brn/controller/AdminController.kt
- src/main/kotlin/com/epam/brn/controller/StudyHistoryController.kt
- src/main/kotlin/com/epam/brn/controller/UserStatisticController.kt
- src/main/kotlin/com/epam/brn/controller/UserStatisticControllerV2.kt
- src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
- src/main/kotlin/com/epam/brn/service/StudyHistoryService.kt
- src/main/kotlin/com/epam/brn/service/statistic/impl/UserDayStatisticService.kt
- src/main/kotlin/com/epam/brn/service/statistic/impl/UserMonthStatisticService.kt
- src/main/kotlin/com/epam/brn/service/statistic/progress/status/impl/UserRestTimeRetrieverImpl.kt
- src/test/kotlin/com/epam/brn/integration/AdminControllerIT.kt
- src/test/kotlin/com/epam/brn/integration/AdminControllerV2IT.kt
- src/test/kotlin/com/epam/brn/integration/StudyHistoryControllerIT.kt
- src/test/kotlin/com/epam/brn/integration/UserStatisticControllerIT.kt
- src/test/kotlin/com/epam/brn/service/StudyHistoryServiceTest.kt
- src/test/kotlin/com/epam/brn/service/statistic/progress/UserDayStatisticServiceTest.kt
- src/test/kotlin/com/epam/brn/service/statistic/progress/UserMonthStatisticServiceTest.kt
- src/test/kotlin/com/epam/brn/service/statistic/progress/status/impl/UserRestTimeRetrieverImplTest.kt
1. Removed deprecated methods:
* /admin/histories
* /status-history/histories
* /admin/study/week
* /statistics/study/week
* /admin/study/year
* /statistics/study/year
2. Change frontend code to use v2 similar methods
3. Remove unused and commented code
> 2265 remove deprecated methods

- src/main/resources/initFiles/subgroups_ru.csv
> 0000 fix db issue

- src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt
- src/test/kotlin/com/epam/brn/service/UserAnalyticsServiceTest.kt
EPMLABSBRN-0000 fix phrases audio file generation
> 0000 fix phrases audio file generation

- frontend/app/components/header/template.hbs
- frontend/app/router.js
- frontend/app/templates/contact.hbs
- frontend/translations/en-us.yaml
- frontend/translations/ru-ru.yaml
> EPMLABSBRN-2276 Add Contact Page with contacts only

- README.md
- frontend-angular/README.md
- frontend-angular/angular.json
- frontend-angular/package.json
- frontend-angular/src/environments/environment.dev.ts
- frontend-angular/src/proxy.conf.dev.json
Added run mode develop: start angular app with localhost backend.
Updated README.md for frontend-angular and root project
> Run angular app with localhost 

- src/main/kotlin/com/epam/brn/service/UrlConversionService.kt
- src/main/kotlin/com/epam/brn/service/load/InitialDataLoader.kt
> fix bug with aws cloud

- src/main/resources/application.properties
> 2312 new aws account

- frontend/app/components/header/template.hbs
- frontend/translations/en-us.yaml
- frontend/translations/ru-ru.yaml
> 000 fix telegram users group

- frontend-angular/src/app/modules/admin/modules/users/users.component.html
- frontend-angular/src/app/modules/shared/pipes/duration-transform.pipe.spec.ts
- frontend-angular/src/app/modules/shared/pipes/duration-transform.pipe.ts
- frontend-angular/src/app/modules/shared/pipes/pipes.module.ts
Convert nanoseconds to hh:mm:ss format and also change "first visit" and 'last visit" fields.
> [UI Angular] Show spentTime in readable view

- src/main/kotlin/com/epam/brn/auth/AuthorityService.kt
- src/main/kotlin/com/epam/brn/auth/AuthorityServiceImpl.kt
- src/main/kotlin/com/epam/brn/controller/DoctorController.kt
- src/main/kotlin/com/epam/brn/controller/RoleController.kt
- src/main/kotlin/com/epam/brn/enums/AuthorityType.kt
- src/main/kotlin/com/epam/brn/service/DoctorService.kt
- src/main/kotlin/com/epam/brn/service/load/InitialDataLoader.kt
- src/test/kotlin/com/epam/brn/controller/RoleControllerTest.kt
- src/test/kotlin/com/epam/brn/integration/DoctorControllerIT.kt
- src/test/kotlin/com/epam/brn/integration/RoleControllerIT.kt
- src/test/kotlin/com/epam/brn/service/DoctorServiceTest.kt
> 2327 add role specialist

- api-contract/api.raml
- src/main/kotlin/com/epam/brn/auth/AuthorityService.kt
- src/main/kotlin/com/epam/brn/auth/AuthorityServiceImpl.kt
- src/main/kotlin/com/epam/brn/controller/ContributorController.kt
- src/main/kotlin/com/epam/brn/controller/ExerciseController.kt
- src/main/kotlin/com/epam/brn/controller/StudyHistoryController.kt
- src/main/kotlin/com/epam/brn/controller/StudyHistoryControllerV2.kt
- src/main/kotlin/com/epam/brn/controller/UserStatisticControllerV2.kt
- src/main/kotlin/com/epam/brn/enums/ContributorType.kt
- src/main/kotlin/com/epam/brn/service/ContributorService.kt
- src/main/kotlin/com/epam/brn/service/ContributorServiceImpl.kt
- src/test/kotlin/com/epam/brn/controller/ContributorControllerTest.kt
- src/test/kotlin/com/epam/brn/controller/ExerciseControllerTest.kt
- src/test/kotlin/com/epam/brn/controller/StudyHistoryControllerTest.kt
- src/test/kotlin/com/epam/brn/controller/StudyHistoryControllerV2Test.kt
- src/test/kotlin/com/epam/brn/controller/UserStatisticControllerV2Test.kt
- src/test/kotlin/com/epam/brn/integration/ContributorControllerIT.kt
- src/test/kotlin/com/epam/brn/service/ContributorServiceTest.kt
2333 change end-point /contributors: return all by default
add new contributors types [DEVELOPER, SPECIALIST,DESIGNER, QA, OTHER]
> 2333 change end-point /contributors: return all by default

- frontend/app/components/header/template.hbs
It was added tooltip by "title" attribute
> 2339 [UI] Add tooltip to Telegram button

- api-contract/api.raml
- src/main/kotlin/com/epam/brn/controller/ResourceController.kt
- src/main/kotlin/com/epam/brn/service/UserAccountService.kt
- src/main/kotlin/com/epam/brn/service/impl/UserAccountServiceImpl.kt
- src/test/kotlin/com/epam/brn/integration/ResourceControllerIT.kt
- src/test/kotlin/com/epam/brn/service/UserAccountServiceTest.kt
> 2324: update raml

- src/main/kotlin/com/epam/brn/dto/SeriesDto.kt
- src/main/kotlin/com/epam/brn/model/Resource.kt
- src/main/kotlin/com/epam/brn/model/Series.kt
- src/main/resources/db/migration/V220221015_1711.sql
> 1711 fix bug, add subgroup sort

- src/main/kotlin/com/epam/brn/dto/github/GitHubUserDto.kt
- src/main/kotlin/com/epam/brn/job/GitHubContributorRefreshJob.kt
- src/main/kotlin/com/epam/brn/repo/ContributorRepository.kt
- src/main/kotlin/com/epam/brn/service/ContributorService.kt
- src/main/kotlin/com/epam/brn/service/ContributorServiceImpl.kt
- src/test/kotlin/com/epam/brn/job/GitHubContributorRefreshJobTest.kt
- src/test/kotlin/com/epam/brn/service/ContributorServiceTest.kt
2281 some ideas to increase readable level and follow single responsibility
> 2281 Some refactoring ideas for contributors sync from github

- src/main/kotlin/com/epam/brn/dto/request/contributor/ContributorRequest.kt
- src/main/kotlin/com/epam/brn/dto/response/ContributorResponse.kt
- src/main/kotlin/com/epam/brn/model/Contributor.kt
- src/main/kotlin/com/epam/brn/service/ContributorServiceImpl.kt
- src/test/kotlin/com/epam/brn/service/ContributorServiceTest.kt
2352 add all fields into ContributorDto
> 2352 add all fields into ContributorDto

- frontend/app/components/task-player/component.ts
- frontend/app/components/task-player/template.hbs
- frontend/app/services/audio.ts
- frontend/app/utils/audio-api.ts
> Preload noize audio

- frontend/app/components/task-player/component.ts
- frontend/app/components/task-player/single-simple-words/component.ts
- frontend/app/components/task-player/words-sequences/component.ts
- frontend/app/utils/answer-option.ts
Resolves https://github.com/Brain-up/brn/issues/2348
> Word Pronounce

- frontend/app/components/about-us/styles.css
- frontend/app/models/contributor.ts
- frontend/app/routes/contributors.ts
- frontend/app/serializers/application.ts
- frontend/app/serializers/contributor.ts
- frontend/app/templates/contributors.hbs
- frontend/app/templates/specialists.hbs
- frontend/translations/en-us.yaml
- frontend/translations/ru-ru.yaml
resolves: https://github.com/Brain-up/brn/issues/2347
> feat/2347 - contributors

- frontend/app/components/series-navigation/template.hbs
resolves: https://github.com/Brain-up/brn/issues/2316
> 2316 - add subgroup subtitles

- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/test/kotlin/com/epam/brn/service/ExerciseServiceTest.kt
2358 Update noiseUrl for all roles
> 2358 Update noiseUrl for all roles

- .github/workflows/create_cert.yml
> Create cert pipeline

- frontend-angular/src/app/modules/admin/models/user.model.ts
- frontend-angular/src/app/modules/admin/modules/users/users.component.html
- frontend-angular/src/app/modules/admin/modules/users/users.component.spec.ts
- frontend-angular/src/app/modules/admin/modules/users/users.component.ts
- frontend-angular/src/app/modules/admin/services/api/admin-api.service.fake.ts
- frontend-angular/src/assets/i18n/en.json
- frontend-angular/src/assets/i18n/ru.json
- src/main/kotlin/com/epam/brn/dto/response/UserWithAnalyticsResponse.kt
- src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt
#2397 
Replaced "Days in last month" by column "Days in current month".
Also now we can see in this column amount of days when user was in our application during current month.
> #2397 BE: show days in current month instead of days for the last month

- src/main/kotlin/com/epam/brn/dto/response/ResourceResponse.kt
- src/main/kotlin/com/epam/brn/model/Resource.kt
- src/main/kotlin/com/epam/brn/repo/ResourceRepository.kt
- src/main/kotlin/com/epam/brn/service/ResourceService.kt
- src/main/kotlin/com/epam/brn/upload/csv/audiometrySpeech/LopotkoRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesMatrix/SeriesMatrixRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesPhrases/SeriesPhrasesRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesWords/SeriesWordsRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesWordsKoroleva/SeriesWordsKorolevaRecordProcessor.kt
- src/main/resources/db/migration/V220221129_2385.sql
- src/test/kotlin/com/epam/brn/integration/ResourceControllerIT.kt
- src/test/kotlin/com/epam/brn/repo/BaseTest.kt
- src/test/kotlin/com/epam/brn/service/ResourceServiceTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/audiometrySpeech/LopotkoRecordProcessorTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/seriesMatrix/SeriesMatrixRecordProcessorTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/seriesWords/SeriesWordsRecordProcessorTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/seriesWordsKoroleva/SeriesWordsKorolevaRecordProcessorTest.kt
> Revert "#2385 BE: remove field audioFileUrl from Resource entity"

- frontend/app/styles/app.css
- frontend/app/templates/group/series/subgroup/exercise.hbs
- frontend/yarn.lock
Resolves https://github.com/Brain-up/brn/issues/2399
Added proper styles
> fix - 2399

- docker-compose-run.yml
- src/main/kotlin/com/epam/brn/service/load/InitialDataLoader.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesMatrix/SeriesMatrixRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesPhrases/SeriesPhrasesRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesWords/SeriesWordsRecordProcessor.kt
- src/main/kotlin/com/epam/brn/upload/csv/seriesWordsKoroleva/SeriesWordsKorolevaRecordProcessor.kt
- src/main/resources/application.properties
- src/test/kotlin/com/epam/brn/integration/CsvLoadingTestIT.kt
- src/test/kotlin/com/epam/brn/upload/csv/seriesMatrix/SeriesMatrixRecordProcessorTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/seriesPhrases/SeriesPhrasesRecordProcessorTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/seriesWords/SeriesWordsRecordProcessorTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/seriesWordsKoroleva/SeriesWordsKorolevaRecordProcessorTest.kt
- src/test/resources/application.properties
> 2422 small refactoring

- frontend/app/index.html
> 2225 update yandex counter

- frontend/app/components/task-player/single-simple-words/option.hbs
- frontend/app/routes/application.ts
- frontend/app/services/audio.ts
fixes https://github.com/Brain-up/brn/issues/2429
> resolves image loading #2429

- frontend/app/components/audio-player/template.hbs
- frontend/app/components/task-player/signal/index.hbs
- frontend/app/modifiers/frequency-visualizer.js
- frontend/app/services/audio.ts
- frontend/vendor/canvas-samples.html
> add frequency visualisation

- src/main/kotlin/com/epam/brn/service/load/InitialDataLoader.kt
- src/main/resources/initFiles/dev/series_phrases_en.csv
- src/main/resources/initFiles/series_phrases_en.csv
2454 add english content phrases
> 2454 add english content phrases

- src/main/kotlin/com/epam/brn/dto/response/TaskResponse.kt
- src/main/kotlin/com/epam/brn/dto/response/TaskWordsGroupResponse.kt
- src/main/kotlin/com/epam/brn/enums/ExerciseType.kt
- src/main/kotlin/com/epam/brn/model/Task.kt
- src/test/kotlin/com/epam/brn/service/TaskServiceTest.kt
2460 add shouldBEWithPicture to TaskDto level
> 2460 add shouldBEWithPicture to TaskDto level

- frontend/app/components/about-us/template.hbs
- frontend/app/components/exercise-type/styles.css
- frontend/app/components/exercise-type/template.hbs
- frontend/app/components/footer/template.hbs
- frontend/app/components/header/styles.css
- frontend/app/components/header/template.hbs
- frontend/app/components/login-form/template.hbs
- frontend/app/components/registration-form/template.hbs
- frontend/app/components/statistics/template.hbs
- frontend/app/templates/groups.hbs
- frontend/app/templates/index.hbs
##2283
Fixed ui errors (login, registration, exercises)
<details>
<summary>Login/Registration</summary>
https://user-images.githubusercontent.com/26000950/219103888-b30879c9-a924-49dd-a376-61048d585cfb.mp4
</details>
<details>
<summary>Exercises</summary>
**Before**
**Now**
https://user-images.githubusercontent.com/26000950/219104512-3c8e6695-ce2c-4b37-a9fd-33cd91941836.mp4
</details>
> Resolves #2283

- frontend/app/components/profile/component.ts
- frontend/app/components/profile/template.hbs
- frontend/app/components/ui/avatars/index.hbs
- frontend/app/components/ui/avatars/index.ts
- frontend/app/services/user-data.ts
- frontend/tests/integration/components/ui/avatars-test.js
##1546
**Avatar selection**:
- Removed saving avatar in localstorage (comes from backend after first save)
- Removed some unnecessary css
- Changed the way it looks a bit because of mobile version (hope it's okay 😄 )
<details>
<summary>How it works</summary>
https://user-images.githubusercontent.com/26000950/219679379-d23ffb47-c90d-4dfb-b477-b7e2db6124d0.mp4
</details>
<details>
<summary>Mobile before</summary>
</details>
<details>
<summary>Mobile now</summary>
</details>
> Resolves #1546

- frontend/app/components/exercise-study-config/index.hbs
- frontend/app/models/task.ts
- frontend/app/services/study-config.ts
- frontend/config/deprecation-workflow.js
- frontend/package.json
- frontend/tests/integration/components/exercise-study-config-test.js
- frontend/tests/integration/components/image-display-block/component-test.js
- frontend/tests/unit/services/study-config-test.js
- frontend/yarn.lock
Resolve https://github.com/Brain-up/brn/issues/2462
> 2462 - opt-out-image display from task model

- frontend/app/index.html
2489 add tag to google analytics
> 2489 add tag to google analytics

- src/main/kotlin/com/epam/brn/dto/ExerciseDto.kt
- src/main/kotlin/com/epam/brn/service/ExerciseService.kt
- src/test/kotlin/com/epam/brn/service/ExerciseServiceTest.kt
2497 fix exercise numbering as list index
> 2497 fix exercise numbering as list index

- src/main/kotlin/com/epam/brn/job/UnverifiedPicturesClearJob.kt
as now it works not correctly - it removes folder unverified
> 000 fix : switch off job, as now it works not correctly - it removes folder unverified

- frontend/tests/integration/components/image-display-block/component-test.js
- src/main/kotlin/com/epam/brn/job/GitHubContributorRefreshJob.kt
- src/main/kotlin/com/epam/brn/job/ResourcePictureUrlUpdateJob.kt
- src/main/kotlin/com/epam/brn/job/UnverifiedPicturesClearJob.kt
- src/main/resources/application.properties
- src/test/kotlin/com/epam/brn/job/ResourcePictureUrlUpdateJobTest.kt
- src/test/kotlin/com/epam/brn/job/UnverifiedPicturesClearJobTest.kt
##2508
fix and switch on job which clear unused pictures, add logs for updating pictures urls job
> 2508  fix and switch on job which clear unused pictures, add logs for updating pictures urls job

- src/main/kotlin/com/epam/brn/dto/statistic/UserDailyDetailStatisticsDto.kt
- src/main/kotlin/com/epam/brn/service/StudyHistoryService.kt
- src/test/kotlin/com/epam/brn/service/StudyHistoryServiceTest.kt
##2479
add duration into UserDailyDetailStatisticsDto
> 2479 add duration field into HistoryDto

- src/main/kotlin/com/epam/brn/controller/CloudController.kt
- src/main/kotlin/com/epam/brn/controller/ExerciseController.kt
- src/main/kotlin/com/epam/brn/controller/UserDetailController.kt
> 2453 Added access in read mode to admin end-points for SPECIALIST role

- frontend-angular/src/app/modules/admin/models/contrubutor.model.ts
- frontend-angular/src/app/modules/admin/modules/contributors/module/contributor/contributor.component.html
- frontend-angular/src/app/modules/admin/modules/contributors/module/contributor/contributor.component.scss
- frontend-angular/src/app/modules/admin/modules/contributors/module/contributor/contributor.component.ts
- frontend-angular/src/app/modules/admin/services/api/contributor-api.service.ts
Implement upload image functionality
> Upload contributor image

- frontend/app/components/task-player/words-sequences/component.ts
Resolves https://github.com/Brain-up/auto-tests-python/issues/126
> Resolve #126

- frontend/app/routes/application.ts
- frontend/app/routes/contributors.ts
- frontend/app/templates/contributors.hbs
- frontend/package.json
- frontend/translations/en-us.yaml
- frontend/translations/ru-ru.yaml
Resolves: https://github.com/Brain-up/brn/issues/2570
> qa-automation group

- .github/workflows/certbot-update-cert.yml
> Add manual run GitHub Action: "Update TLS certificates for vscale"

- frontend-angular/src/app/modules/admin/modules/users/modules/statistics/statistics.component.html
- frontend-angular/src/app/modules/admin/modules/users/modules/statistics/statistics.component.scss
- frontend-angular/src/app/modules/admin/modules/users/users.component.html
- frontend-angular/src/app/modules/admin/modules/users/users.component.ts
- frontend-angular/src/assets/i18n/en.json
- frontend-angular/src/assets/i18n/ru.json
> feat(2594): adds email column & makes email selectable 

- src/main/kotlin/com/epam/brn/auth/filter/FirebaseTokenAuthenticationFilter.kt
- src/main/kotlin/com/epam/brn/service/TaskService.kt
- src/main/kotlin/com/epam/brn/service/load/FirebaseUserDataLoader.kt
- src/test/kotlin/com/epam/brn/integration/AuthorizationAuthenticationIT.kt
- src/test/kotlin/com/epam/brn/integration/repo/BaseTest.kt
- src/test/kotlin/com/epam/brn/integration/repo/TaskRepositoryTest.kt
- src/test/kotlin/com/epam/brn/integration/repo/UserAccountRepositoryTest.kt
> 2657 temp version for s3 substitution

- src/main/kotlin/com/epam/brn/controller/ResourceController.kt
##2672
BE fix permissions for resources end-points
> BE fix permissions for resources end-points

- src/main/kotlin/com/epam/brn/enums/Voice.kt
- src/main/kotlin/com/epam/brn/service/WordsService.kt
- src/main/kotlin/com/epam/brn/service/YandexSpeechKitService.kt
- src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt
- src/test/kotlin/com/epam/brn/service/UserAnalyticsServiceTest.kt
> BE update voices

- src/main/kotlin/com/epam/brn/enums/BrnGender.kt
- src/main/kotlin/com/epam/brn/model/Audiometry.kt
- src/main/kotlin/com/epam/brn/model/AudiometryHistory.kt
- src/main/kotlin/com/epam/brn/model/AudiometryTask.kt
- src/main/kotlin/com/epam/brn/model/Contact.kt
- src/main/kotlin/com/epam/brn/model/Contributor.kt
- src/main/kotlin/com/epam/brn/model/Exercise.kt
- src/main/kotlin/com/epam/brn/model/ExerciseGroup.kt
- src/main/kotlin/com/epam/brn/model/GitHubUser.kt
- src/main/kotlin/com/epam/brn/model/Headphones.kt
- src/main/kotlin/com/epam/brn/model/Notification.kt
- src/main/kotlin/com/epam/brn/model/Resource.kt
- src/main/kotlin/com/epam/brn/model/Role.kt
- src/main/kotlin/com/epam/brn/model/Series.kt
- src/main/kotlin/com/epam/brn/model/Signal.kt
- src/main/kotlin/com/epam/brn/model/SinAudiometryResult.kt
- src/main/kotlin/com/epam/brn/model/StudyHistory.kt
- src/main/kotlin/com/epam/brn/model/SubGroup.kt
- src/main/kotlin/com/epam/brn/model/Task.kt
- src/main/kotlin/com/epam/brn/model/UserAccount.kt
- src/test/kotlin/com/epam/brn/service/UserAccountServiceTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/audiometrySpeech/LopotkoRecordProcessorTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/seriesMatrix/SeriesMatrixRecordProcessorTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/seriesWords/SeriesWordsRecordProcessorTest.kt
- src/test/kotlin/com/epam/brn/upload/csv/seriesWordsKoroleva/SeriesWordsKorolevaRecordProcessorTest.kt
##2311
fix jpa classes: delete data from them
> fix jpa classes: delete data modificator from them, fix tests

- README.md
> Update README.md delete old links

- README.md
> Update README.md to redeploy server

- src/main/kotlin/com/epam/brn/job/ResourcePictureUrlUpdateJob.kt
- src/main/kotlin/com/epam/brn/service/TaskService.kt
- src/main/kotlin/com/epam/brn/service/cloud/AwsCloudService.kt
- src/main/kotlin/com/epam/brn/service/cloud/CloudService.kt
- src/main/kotlin/com/epam/brn/service/cloud/GoogleCloudService.kt
- src/test/kotlin/com/epam/brn/job/ResourcePictureUrlUpdateJobTest.kt
- src/test/kotlin/com/epam/brn/service/cloud/AwsCloudServiceTest.kt
##2430 
build task picture url by using resource.pictureFileUrl that is set in ResourcePictureUrlUpdateJob
> 2430 Build task picture url by using resource.pictureFileUrl that is set in ResourcePictureUrlUpdateJob

- .github/workflows/java-ci.yml
- build.gradle.kts
CI/CD pipeline: SONAR_TOKEN passed through pipeline to gradle, sonarqube plugin version bump 3.0->6.2
> CI/CD pipeline: SONAR_TOKEN passed through pipeline to gradle, sonarqube plugin version bump 3.0->6.2

- .github/workflows/frontend-admin.yml
- .github/workflows/frontend-app-test.yml
- .github/workflows/java-ci.yml
> Revert "secrets.GITHUB_TOKEN -> secrets.API_GITHUB_TOKEN"
