Brain-up/brn

Dockerfile_test
Makefile
docker-compose-unit-test.yml
src/main/resources/application-dev.properties
src/main/resources/application-prod.properties

[EPMLABSBRN-37](https://jira.epam.com/jira/browse/EPMLABSBRN-37)
Application Dockerization tuning.
Extracting unit tests execution to the separate compose file leads to the fact that we have a single point of truth in all possible situations when we have different results in test execution (at the environment side vs on local machines under Windows/Linux/macOS).
Makefile should make our workflow a bit more comfortable, especially in the case when someone a bit non-familiar with some specific commands and keys and we need to save our time and just use 
**make [command]** instead of a bit longer one.

EPMLABSBRN-37 upgrade dockerization

---

src/main/kotlin/com/epam/brn/controller/SeriesController.kt
src/main/kotlin/com/epam/brn/dto/ExerciseGroupDto.kt
src/main/kotlin/com/epam/brn/dto/SeriesDto.kt
src/main/kotlin/com/epam/brn/model/ExerciseGroup.kt
src/main/kotlin/com/epam/brn/model/Series.kt
src/main/kotlin/com/epam/brn/service/SeriesService.kt
src/test/kotlin/com/epam/brn/controller/SeriesControllerTest.kt
src/test/kotlin/com/epam/brn/integration/SeriesControllerIT.kt
src/test/kotlin/com/epam/brn/service/SeriesServiceTest.kt

EPMLABSBRN-105 Back-end: support child ids by defualt in GET requests for groups&series
Description
response include child ids

EPMLABSBRN-105  Back-end: support child ids by defualt in GET requests for groups&series

---

src/main/kotlin/com/epam/brn/constant/BrnPath.kt
src/main/resources/application.properties

EPMLABSBRN-136 add `/api` to all end-points
fixed: add property to application.property for it

EPMLABSBRN-136 add `/api` to all end-points

---

.githooks/commit-msg

[EPMLABSBRN-254](https://jira.epam.com/jira/browse/EPMLABSBRN-254)
fix for commit-msg hook

EPMLABSBRN-254 fix for commit-msg hook

---

.gitattributes

.gitattributes file in general controls
line ending on repository level and prevents
related error on different OS without need
of additional tools.
Without it people on different OS very likely will face issues
when IDE/editor automatically change line endings that lead
to full file modification.
It listing binaries files and can be used to set LF/CRLF
endings explicitly for each format.
See https://git-scm.com/docs/gitattributes for details

EPMLABSBRN-0 add .gitattributes file

---

src/main/kotlin/com/epam/brn/config/AwsConfig.kt
src/main/kotlin/com/epam/brn/service/impl/AwsCloudService.kt
src/test/kotlin/com/epam/brn/service/impl/AwsCloudServiceTest.kt

Described classes are higly coupled that makes
testing of AwsCloudService harder and requires
mocks on data structures.
In general mocking data structures is anti-pattern
and we should avoid such coding, as it signalizes
us that code have smells and have high coupling.
Instead we need to get rid of such hard links
between classes if they are meant to be used
separately.
As simple solution for now is to change Conditions class
from inner to outer and open for world. In order to decouple
it from parent we need to pass all required params
to constructor or builder class.
There are few formatting changes as well.

Epmlabsbrn 311 refactoring aws config

---

src/main/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdvice.kt
src/test/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdviceTest.kt

EPMLABSBRN-311 update log levels
For all cases that are not actual errors from user perspective
log level was changed from `error` to `warn`
(i.e. user can upload not valid info, or pass not valid param
as part of normal program execution).
EPMLABSBRN-311 refactor ExceptionControllerAdvice
- inline methods with 1 usage
- extract duplicated code to separate method
EPMLABSBRN-311 remove unused code <eom>

Epmlabsbrn 311 refactoring and issues exception advice

---

src/main/kotlin/com/epam/brn/controller/StudyHistoryController.kt
src/main/kotlin/com/epam/brn/converter/StudyHistoryConverter.kt
src/main/kotlin/com/epam/brn/dto/StudyHistoryDto.kt
src/main/kotlin/com/epam/brn/repo/ExerciseRepository.kt
src/main/kotlin/com/epam/brn/service/StudyHistoryService.kt
src/test/kotlin/com/epam/brn/controller/StudyHistoryControllerTest.kt
src/test/kotlin/com/epam/brn/service/StudyHistoryServiceTest.kt

[EPMLABSBRN-221](https://jira.epam.com/jira/browse/EPMLABSBRN-221)
500 error was returned because of DB constraint violation. That happened because of missing non-existing dependent entities check, like Exercise and UserAccount. Now if wrong ids are passed and no entities were found correct exception is thrown.

EPMLABSBRN-221 rework StudyHistoryService to correctly handle incorrect user/exercise ids <eom>

---

api-contract/samples/authSuchUserAlreadyExistErrorResponse.json
src/main/kotlin/com/epam/brn/service/impl/UserAccountServiceImpl.kt

[EPMLABSBRN-430](https://jira.epam.com/jira/browse/EPMLABSBRN-430)
**Current state**:
we send emails in the body of error message. We have to remove it from the message. Example:
`User with email admin@admin.com already exists!`
**After fix**:
`The user already exists`

EPMLABSBRN-430: removing email from message

---

src/main/kotlin/com/epam/brn/config/WebMvcBasicConfiguration.kt
src/main/kotlin/com/epam/brn/controller/GroupController.kt
src/main/kotlin/com/epam/brn/dto/ExerciseGroupDto.kt
src/main/kotlin/com/epam/brn/service/GroupLocalePostprocessorImpl.kt
src/main/kotlin/com/epam/brn/service/LocalePostprocessor.kt
src/main/resources/messages.properties
src/main/resources/messages_en.properties
src/main/resources/messages_ru.properties
src/test/kotlin/com/epam/brn/controller/GroupControllerTest.kt

[EPMLABSBRN-497](https://jira.epam.com/jira/browse/EPMLABSBRN-497)
**Internalization was implemented for requests to get exercise groups**
For implementation was used a map to store the mapping:
- group name (unique) **to** messages
This solution includes a common spring approach, but the other part is temporary and to implement full internalization flow, translate of elements should be added initially by an operator and saved to the database or translate should be used from messages.properties
Examples:
- api/groups?locale=en_EN
- api/groups?locale=ru_RU

Epmlabsbrn-497 [Demo] add multilanguage support for grous

---

.github/workflows/docker-build-push-redeploy.yml
.github/workflows/docker-build.yml

devops: parallel build front and back on cicd github actions
[EPMLABSBRN-570](https://jira.epam.com/jira/browse/EPMLABSBRN-570)
To increase speed of build and publish docker images changing it from sequence to parallel jobs. It will decrease time of deployment waiting

EPMLABSBRN-570: devops: parallel build frontend and backend in parallel 

---

src/main/kotlin/com/epam/brn/dto/NoiseDto.kt

[EPMLABSBRN-582](https://jira.epam.com/jira/browse/EPMLABSBRN-582)
Change the NoiseDto's fields names
NoiseDto should have the body with the following fields :
`data class NoiseDto(
var level: Int = 0,
var url: String? = null
)
`

EPMLABSBRN-582 Change the NoiseDto's fields names

---

.github/workflows/java-ci.yml

Fix of issue from 
https://github.com/Brain-up/brn/runs/1588229328
> Please add the secret GITHUB_TOKEN as an environment variable to your GitHub Actions workflow. See https://github.com/sonarsource/sonarcloud-github-action for more details.

Added GITHUB_TOKEN to env variables for sonarcloud integration

---

default_with_tls.conf

[EPMLABSBRN-654](https://jira.epam.com/jira/browse/EPMLABSBRN-654)
Removed errors showing via HTTP
Added particular server name, to avoid redirection to localhost

Update default_with_tls.conf to improve redirect from HTTP to HTTPS

---

frontend/app/components/header/component.ts
frontend/app/components/header/template.hbs
frontend/tests/integration/components/header/component-test.js

+ getter activeLocale added into the header component
#2023

[frontend] 2023: Description & locale buttons are transparent if user is not logged in

---

.github/workflows/docker-build-push-redeploy.yml

We have errors during requests to download images from dockerhub such as:
```
ERROR: for brn  toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
like here: https://github.com/Brain-up/brn/runs/2977823066
To mitigate the issue, I temporarly disabled deploy for epam instance.
But in the future, possible solution is move out from dockerhub to some other docker registry, for example github packages https://github.com/features/packages

Disable epam instance deploy because of dockerhub pull limits in epam network

---

.github/workflows/java-ci.yml
.gitignore

[EPMLABSBRN-887](https://jira.epam.com/jira/browse/EPMLABSBRN-887)
Save cicd artifacts such integration test reports for ability to see them
as now MR falls
https://github.com/Brain-up/brn/pull/2031
and we can't see such reports

[EPMLABSBRN-887] [DevOps] Save cicd artifacts such integration test reports for ability to see them

---

build.gradle
gradle.properties

Builds will no longer be able to resolve artifacts from JCenter after February 1st, 2022

EPMLABSBRN-908 BE: Change jcenter() to mavenCentral()

---

build.gradle
gradle.properties

this should fix CVE-2020-9488 Improper Certificate Validation

EPMLABSBRN-493 update log4j-api-kotlin 1.0.0 -> 1.1.0

---

frontend/translations/en-us.yaml

##2516
[Bug] A typo in the name of the "Contacts" section in the navbar menu in English version
Fix:
Changed the 'Contact' spelling to   'Contacts' in the header.

fix: typo in header

---

frontend-angular/src/app/modules/admin/modules/contributors/contributors.component.html
frontend-angular/src/app/modules/admin/modules/contributors/contributors.component.ts
frontend-angular/src/assets/i18n/en.json

##2502
Added Active/Inactive column to the table in contributors page.

add active column to contributors table

---

frontend/app/components/task-player/single-simple-words/component.ts

resolves https://github.com/Brain-up/brn/issues/2555

expose-correct-answer-for-testingg

---

.github/workflows/java-ci.yml
Dockerfile
Dockerfile_test
build.gradle.kts
src/test/kotlin/com/epam/brn/controller/advice/ExceptionControllerAdviceTest.kt

##2590
**Updated Java JDK from 11 to 17**:
- Updated Java JDK used in backend app
- Updated Java JDK used in pipeline `Java CI Build, Unit and Integration Tests`
- Updated Java JDK used in old tests triggered via makefile in `docker-compose-unit-test.yml`

Updated Java JDK from 11 to 17 used in backend app

---

src/main/kotlin/com/epam/brn/job/AutoTestUsersDeletionJob.kt
src/main/kotlin/com/epam/brn/service/impl/UserAccountServiceImpl.kt
src/main/resources/application.properties
src/test/kotlin/com/epam/brn/integration/UserDetailsControllerIT.kt
src/test/kotlin/com/epam/brn/job/AutoTestUsersDeletionJobTest.kt
src/test/kotlin/com/epam/brn/service/UserAccountServiceTest.kt
src/test/resources/application.properties

##2592
**2592 [BE] job for deleting autotest contributors**:

2592 [BE] job for deleting autotest contributors

---

.github/workflows/certbot-update-cert.yml
.github/workflows/create_cert.yml
.github/workflows/docker-build-push-redeploy.yml
.github/workflows/instances-redeploy.yml_tmp
Dockerfile
Dockerfile_frontend
Dockerfile_frontend_with_tls
Makefile
README.md
docker-compose-run.yml
docker-compose-unit-test.yml
docker-compose-with-secret.yml
docker-compose.yml

Update docker-compose to use as a plugin instead of separate tool

Update docker-compose to use as plugin instead of separate tool

---

.github/workflows/docker-build-push-redeploy.yml

Right now we have two images for frontend app - one with tls and one without. Right now without tls not used. So to reduce time of building on master branch, I've decided to remove building frontend app without tls, as it is not used anymore after removal of epam instance

Remove separate frontend image from building process

---

src/main/kotlin/com/epam/brn/dto/SeriesDto.kt
src/main/kotlin/com/epam/brn/model/Series.kt
src/main/kotlin/com/epam/brn/repo/SeriesRepository.kt
src/main/kotlin/com/epam/brn/service/SeriesService.kt
src/main/resources/db/migration/V220250909_2592.sql
src/test/kotlin/com/epam/brn/integration/SeriesControllerIT.kt
src/test/kotlin/com/epam/brn/service/SeriesServiceTest.kt

2595
I added new active field into Series model. I also added tests for new field

2595 - add active field into series model, add tests for new field
